package com.gridstore.huevista.account.service;

import com.gridstore.huevista.account.dto.AccessCodeResponse;
import com.gridstore.huevista.account.dto.AssignedProductsResponse;
import com.gridstore.huevista.account.dto.GenerateAccessCodeRequest;
import com.gridstore.huevista.account.dto.GuestRedeemResponse;
import com.gridstore.huevista.account.dto.RedeemAccountResponse;
import com.gridstore.huevista.account.model.CustomerAccessCode;
import com.gridstore.huevista.account.model.OrgMemberRole;
import com.gridstore.huevista.account.model.OrgType;
import com.gridstore.huevista.account.model.Organization;
import com.gridstore.huevista.account.repository.CustomerAccessCodeRepository;
import com.gridstore.huevista.account.repository.OrgMembershipRepository;
import com.gridstore.huevista.account.repository.OrganizationRepository;
import com.gridstore.huevista.auth.dto.AuthResponse;
import com.gridstore.huevista.auth.model.AuthProvider;
import com.gridstore.huevista.auth.model.User;
import com.gridstore.huevista.auth.model.UserRole;
import com.gridstore.huevista.auth.repository.UserRepository;
import com.gridstore.huevista.auth.service.AuthService;
import com.gridstore.huevista.billing.model.Subscription;
import com.gridstore.huevista.billing.model.SubscriptionStatus;
import com.gridstore.huevista.billing.repository.SubscriptionRepository;
import com.gridstore.huevista.common.exception.QuotaExceededException;
import com.gridstore.huevista.common.exception.ResourceNotFoundException;
import com.gridstore.huevista.paint.dto.ShopProductResponse;
import com.gridstore.huevista.paint.repository.ShopProductRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.security.SecureRandom;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;
import java.util.Optional;

@Slf4j
@Service
@RequiredArgsConstructor
public class AccessCodeService {

    private final CustomerAccessCodeRepository codeRepository;
    private final OrganizationRepository orgRepository;
    private final OrgMembershipRepository membershipRepository;
    private final UserRepository userRepository;
    private final CustomerEntitlementService entitlementService;
    private final com.gridstore.huevista.auth.service.JwtService jwtService;
    private final AuthService authService;
    private final SubscriptionRepository subscriptionRepository;
    private final com.gridstore.huevista.billing.service.BillingService billingService;
    private final com.gridstore.huevista.common.audit.AuditService auditService;
    private final BrandAccessService brandAccessService;
    private final ShopProductRepository shopProductRepository;
    private final com.gridstore.huevista.project.repository.ProjectRepository projectRepository;

    private static final String CODE_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"; // no ambiguous chars
    private static final int CODE_LENGTH = 8;
    private static final SecureRandom RANDOM = new SecureRandom();

    /** Retailer-assigned customer codes are always valid for 10 days. */
    private static final int FIXED_VALID_DAYS = 10;

    @Transactional
    public AccessCodeResponse generateCode(String requestingUserId, String orgId, GenerateAccessCodeRequest request) {
        Organization org = orgRepository.findById(orgId)
                .orElseThrow(() -> new ResourceNotFoundException("Organization not found: " + orgId));

        if (org.getType() != OrgType.RETAILER) {
            throw new IllegalArgumentException("Access codes can only be generated by retailer organizations");
        }

        requireOwnerOrManager(requestingUserId, orgId);

        // A shop may only hand on companies its distributor actually assigned it —
        // otherwise the whole assign/revoke feature is decorative, since a retailer could
        // unlock any brand on a code regardless of what they carry.
        brandAccessService.assertBrandsOfferable(orgId, request.getAllowedBrands());

        // Validate the individually-unlocked products actually belong to this shop, so a
        // crafted request can't unlock a competitor's listing.
        List<String> productIds = request.getAllowedProductIds();
        if (productIds != null) {
            for (String pid : productIds.stream().distinct().toList()) {
                shopProductRepository.findByIdAndOrganizationId(pid, orgId)
                        .orElseThrow(() -> new ResourceNotFoundException(
                                "Product is not one of this shop's listings: " + pid));
            }
        }

        // Charge the assigned projects against the retailer OWNER's monthly image quota
        // BEFORE creating the code — one image reserved per assigned project. A single
        // atomic all-or-nothing reservation; if it won't fit, nothing is charged.
        reserveProjectQuota(orgId, request.getProjectQuota());

        String code = generateUniqueCode();
        LocalDateTime expiresAt = LocalDateTime.now().plusDays(FIXED_VALID_DAYS);

        CustomerAccessCode accessCode = CustomerAccessCode.builder()
                .organization(org)
                .code(code)
                .validDays(FIXED_VALID_DAYS)
                .expiresAt(expiresAt)
                .customerName(request.getCustomerName().trim())
                .projectQuota(request.getProjectQuota())
                // One held image credit per assigned project. Spent as projects are
                // actually segmented; returned to the shop if the code is revoked or
                // expires with nobody redeeming it.
                .reservedImages(request.getProjectQuota())
                .build();
        accessCode.setAllowedBrandList(request.getAllowedBrands());
        accessCode.setAllowedProductIdList(productIds);
        accessCode = codeRepository.save(accessCode);

        log.info("Access code generated: org={} code={} customer={} quota={} brands={} products={}",
                orgId, code, accessCode.getCustomerName(), accessCode.getProjectQuota(),
                accessCode.getAllowedBrandList(), accessCode.getAllowedProductIdList().size());
        return withAssignedProducts(accessCode);
    }

    /**
     * Reserve {@code projectQuota} images against the retailer owner's ACTIVE subscription
     * (one image per assigned project). Throws {@link QuotaExceededException} when the shop
     * has no active plan or not enough remaining quota — the retailer must top up or assign
     * fewer projects.
     */
    private void reserveProjectQuota(String orgId, int projectQuota) {
        String ownerId = resolveOrgOwnerUserId(orgId);
        Subscription sub = subscriptionRepository
                .findEntitling(ownerId, SubscriptionStatus.ACTIVE, SubscriptionStatus.CANCELLED,
                        LocalDateTime.now())
                .stream().findFirst()
                .orElseThrow(() -> new QuotaExceededException(
                        "No active subscription. Subscribe to a plan before assigning projects to customers."));
        if (subscriptionRepository.reserveImagesIfWithinLimit(sub.getId(), projectQuota) == 0) {
            throw new QuotaExceededException(
                    "Not enough image quota to assign " + projectQuota + " project"
                    + (projectQuota == 1 ? "" : "s") + ". Buy more images or assign fewer.");
        }
        log.info("Held {} image(s) on subscription {} for access-code assignment", projectQuota, sub.getId());
    }

    /**
     * Hand a code's unspent image credits back to the issuing shop. Idempotent: the
     * {@code quotaReleasedAt} compare-and-set means a revoke racing the expiry sweep
     * refunds exactly once. Returns how many credits went back.
     */
    private int releaseHeldQuota(CustomerAccessCode code) {
        int held = code.getReservedImages();
        if (held <= 0) {
            codeRepository.markQuotaReleased(code.getId(), LocalDateTime.now());
            return 0;
        }
        if (codeRepository.markQuotaReleased(code.getId(), LocalDateTime.now()) == 0) {
            return 0; // someone else already refunded this code
        }
        resolveOrgOwnerUserIdOptional(code.getOrganization().getId())
                .ifPresent(ownerId -> billingService.releaseReservedImages(ownerId, held));
        log.info("Released {} held image(s) back to shop {} from code {}",
                held, code.getOrganization().getId(), code.getCode());
        return held;
    }

    /**
     * Cancel a code the shop issued but nobody has redeemed yet, returning its unspent
     * image credits to the shop's quota.
     *
     * Without this a mistyped customer name or a wrong project count could only be fixed
     * by issuing a SECOND code — paying the quota twice — while the wrong one stayed live
     * for its full 10 days. A code that has already been redeemed is deliberately NOT
     * revocable: the customer may already have work under it, and pulling access after
     * the fact would strand them mid-visit at the counter.
     */
    @Transactional
    public AccessCodeResponse revokeCode(String requestingUserId, String codeId) {
        CustomerAccessCode code = codeRepository.findById(codeId)
                .orElseThrow(() -> new ResourceNotFoundException("Access code not found: " + codeId));
        requireOwnerOrManager(requestingUserId, code.getOrganization().getId());

        if (code.isUsed()) {
            throw new IllegalStateException(
                    "This code has already been redeemed, so it can't be cancelled. "
                    + "The customer's access ends on its own when the code expires.");
        }
        if (codeRepository.revokeIfUnused(codeId, LocalDateTime.now()) == 0) {
            throw new IllegalStateException("This code was already cancelled or redeemed.");
        }
        int returned = releaseHeldQuota(code);

        auditService.record(requestingUserId, "ACCESS_CODE_REVOKED", "ACCESS_CODE", codeId,
                "org=" + code.getOrganization().getId() + " code=" + code.getCode()
                        + " imagesReturned=" + returned);
        log.info("Access code revoked: org={} code={} imagesReturned={}",
                code.getOrganization().getId(), code.getCode(), returned);
        return AccessCodeResponse.from(codeRepository.findById(codeId).orElse(code));
    }

    /**
     * Amend a code that has not been redeemed yet: the customer's name, and which
     * companies / individual products it unlocks.
     *
     * The assigned project count is deliberately NOT editable here — it is backed by held
     * image credits, and re-reserving mid-flight is a second money path for very little
     * benefit. To change the count, cancel the code (quota comes back) and issue a new one.
     */
    @Transactional
    public AccessCodeResponse updateCode(String requestingUserId, String codeId,
                                         GenerateAccessCodeRequest request) {
        CustomerAccessCode code = codeRepository.findById(codeId)
                .orElseThrow(() -> new ResourceNotFoundException("Access code not found: " + codeId));
        String orgId = code.getOrganization().getId();
        requireOwnerOrManager(requestingUserId, orgId);

        if (code.isUsed()) {
            throw new IllegalStateException(
                    "This code has already been redeemed — its assignment can no longer be changed.");
        }
        if (code.isRevoked()) {
            throw new IllegalStateException("This code was cancelled.");
        }

        brandAccessService.assertBrandsOfferable(orgId, request.getAllowedBrands());
        List<String> productIds = request.getAllowedProductIds();
        if (productIds != null) {
            for (String pid : productIds.stream().distinct().toList()) {
                shopProductRepository.findByIdAndOrganizationId(pid, orgId)
                        .orElseThrow(() -> new ResourceNotFoundException(
                                "Product is not one of this shop's listings: " + pid));
            }
        }
        code.setCustomerName(request.getCustomerName().trim());
        code.setAllowedBrandList(request.getAllowedBrands());
        code.setAllowedProductIdList(productIds);
        codeRepository.save(code);

        auditService.record(requestingUserId, "ACCESS_CODE_UPDATED", "ACCESS_CODE", codeId,
                "org=" + orgId + " code=" + code.getCode());
        log.info("Access code updated: org={} code={}", orgId, code.getCode());
        return withAssignedProducts(code);
    }

    /**
     * Daily sweep: hand back the image credits held by codes that expired without anyone
     * redeeming them. A shop pays a credit per assigned project the moment it prints a
     * code; when the customer never walks back in, that credit used to stay held forever.
     *
     * Runs an hour after the subscription expiry job so the two never interleave on the
     * same rows. Each code is refunded in its own transaction — one bad row must not
     * abort the whole sweep.
     */
    @org.springframework.scheduling.annotation.Scheduled(cron = "0 0 2 * * *")
    public void releaseExpiredCodeQuota() {
        List<CustomerAccessCode> stale =
                codeRepository.findExpiredUnredeemedWithHolds(LocalDateTime.now());
        if (stale.isEmpty()) return;
        int refunded = 0;
        for (CustomerAccessCode code : stale) {
            try {
                refunded += releaseHeldQuotaInNewTransaction(code.getId());
            } catch (Exception e) {
                log.warn("Could not release held quota for expired code {}: {}",
                        code.getId(), e.getMessage());
            }
        }
        log.info("Expired-code sweep returned {} image credit(s) across {} code(s)",
                refunded, stale.size());
    }

    @Transactional(propagation = org.springframework.transaction.annotation.Propagation.REQUIRES_NEW)
    public int releaseHeldQuotaInNewTransaction(String codeId) {
        return codeRepository.findById(codeId).map(this::releaseHeldQuota).orElse(0);
    }

    @Transactional(readOnly = true)
    public List<AccessCodeResponse> listCodes(String requestingUserId, String orgId) {
        requireOwnerOrManager(requestingUserId, orgId);
        List<AccessCodeResponse> codes = codeRepository.findByOrganizationIdOrderByCreatedAtDesc(orgId).stream()
                .map(AccessCodeResponse::from)
                .toList();
        // The shop pays an image per assigned project, so the list has to show the
        // quota counting down as the customer creates rooms. One grouped query for
        // the whole page rather than a COUNT per code.
        Map<String, Long> usedByCode = countProjectsByCode(codes.stream().map(AccessCodeResponse::getId).toList());
        codes.forEach(c -> c.applyProjectsUsed(usedByCode.getOrDefault(c.getId(), 0L).intValue()));
        return codes;
    }

    /** Rooms created per access code, keyed by code id. Empty input short-circuits
     *  (JPQL rejects an empty {@code IN ()} list). */
    private Map<String, Long> countProjectsByCode(List<String> codeIds) {
        if (codeIds.isEmpty()) return Map.of();
        return projectRepository.countByAccessCodeIds(codeIds).stream()
                .collect(java.util.stream.Collectors.toMap(
                        row -> (String) row[0], row -> ((Number) row[1]).longValue()));
    }

    /**
     * Redeems an access code for an existing authenticated user.
     * Sets the user role to CUSTOMER and links them to the retailer's org.
     */
    @Transactional
    public AccessCodeResponse redeemCode(String userId, String code) {
        CustomerAccessCode accessCode = codeRepository.findByCode(code.toUpperCase())
                .orElseThrow(() -> new ResourceNotFoundException("Access code not found: " + code));

        if (accessCode.isUsed()) {
            throw new IllegalStateException("This access code has already been used");
        }
        if (accessCode.isRevoked()) {
            throw new IllegalStateException("This access code was cancelled by the shop");
        }
        if (accessCode.isExpired()) {
            throw new IllegalStateException("This access code has expired");
        }

        User user = userRepository.findById(userId)
                .orElseThrow(() -> new ResourceNotFoundException("User not found"));

        // Redeeming flips the account to CUSTOMER — for a shop, distributor, painter
        // or admin account that would silently destroy their real role (and with it
        // org ownership checks, subscriptions, the admin console…). Public signups
        // are CUSTOMER already, so only customers ever legitimately redeem here.
        if (user.getRole() != null && user.getRole() != UserRole.CUSTOMER) {
            throw new IllegalStateException(
                    "This account is a " + user.getRole().name().toLowerCase()
                    + " account — access codes are for walk-in customers. "
                    + "Ask your customer to redeem it, or open it in a private window.");
        }

        // Compare-and-set consumption: if a concurrent request redeemed this code
        // between our isUsed() check and here, the guarded UPDATE matches 0 rows.
        LocalDateTime now = LocalDateTime.now();
        if (codeRepository.consumeForUser(accessCode.getId(), user, now) == 0) {
            throw new IllegalStateException("This access code has already been used");
        }

        user.setRole(UserRole.CUSTOMER);
        userRepository.save(user);

        // Mirror what the UPDATE wrote so the response (and any flush) is consistent.
        accessCode.setUsedByUser(user);
        accessCode.setUsedAt(now);

        // Create/refresh the customer's project entitlement: the assigned quota, valid for validDays.
        entitlementService.onAccessCodeRedeemed(user, accessCode.getOrganization(),
                accessCode.getValidDays(), accessCode.getProjectQuota());

        log.info("Access code redeemed: user={} org={} code={}", userId, accessCode.getOrganization().getId(), code);
        return AccessCodeResponse.from(accessCode);
    }

    /**
     * Redeems a retailer access code with NO login: auto-provisions a passwordless
     * CUSTOMER account named as the retailer entered, signs it in, and returns a full
     * session. The customer lands on their dashboard with their own name and their
     * assigned project quota + products.
     *
     * RE-ENTRY: because the account has no password, a customer who loses their session
     * (dead phone, closed tab) must be able to get back in with the same code while it is
     * valid. So a code already redeemed into an account re-mints a session for that SAME
     * account rather than stranding them — the entitlement is NOT reset, so any projects
     * they already created are preserved. One account per code; a code consumed by the
     * signed-in role-flip path ({@link #redeemCode}) stays as-is.
     */
    @Transactional
    public RedeemAccountResponse redeemAsNewCustomer(String code) {
        CustomerAccessCode accessCode = codeRepository.findByCode(code.toUpperCase())
                .orElseThrow(() -> new ResourceNotFoundException("Access code not found: " + code));

        if (accessCode.isRevoked()) {
            throw new IllegalStateException("This access code was cancelled by the shop");
        }
        if (accessCode.isExpired()) {
            throw new IllegalStateException("This access code has expired");
        }

        // A code already consumed by an ACCOUNT can only be re-entered by that same
        // auto-provisioned customer account (re-entry). A guest-consumed legacy code has
        // no account to sign into here.
        if (accessCode.getUsedByUser() != null) {
            User existing = accessCode.getUsedByUser();
            if (existing.getProvider() != AuthProvider.ACCESS_CODE) {
                throw new IllegalStateException("This access code has already been used");
            }
            // Re-entry must not reset the allowance, but the account MUST end up with an
            // entitlement: without one every project read answers 403 "Your access is not
            // set up" and the customer is signed in to a dashboard that can load nothing.
            entitlementService.ensureEntitlementForCode(existing, accessCode);
            AuthResponse session = authService.buildAuthResponse(existing);
            log.info("Access code re-entered by customer account: user={} code={}", existing.getId(), code);
            return toRedeemResponse(session, accessCode);
        }
        if (accessCode.isUsed()) {
            throw new IllegalStateException("This access code has already been used");
        }

        // First redemption: create the account, consume the code, set the entitlement. The
        // synthetic e-mail is derived from the code, so an account left behind by an earlier
        // partial redemption is found here and simply signed back in.
        String email = customerEmailForCode(accessCode.getCode());
        Optional<User> orphaned = userRepository.findByEmail(email);
        if (orphaned.isPresent() && orphaned.get().getProvider() == AuthProvider.ACCESS_CODE) {
            User owner = orphaned.get();
            // The account exists but the code was never consumed, so the earlier redemption
            // stopped half-way. Finish it here instead of handing back a session that owns
            // nothing: claim the code for this account (the e-mail is derived from the code,
            // so it can belong to no one else) and make sure the entitlement is in place.
            // Losing the compare-and-set means someone else consumed it concurrently — the
            // account is still this code's, so sign them in anyway.
            LocalDateTime consumedAt = LocalDateTime.now();
            if (codeRepository.consumeForUser(accessCode.getId(), owner, consumedAt) == 1) {
                accessCode.setUsedByUser(owner);
                accessCode.setUsedAt(consumedAt);
            }
            entitlementService.ensureEntitlementForCode(owner, accessCode);
            AuthResponse session = authService.buildAuthResponse(owner);
            log.info("Access code re-entered by existing customer account: user={} code={}", owner.getId(), code);
            return toRedeemResponse(session, accessCode);
        }

        User customer;
        try {
            customer = userRepository.saveAndFlush(User.builder()
                    .name(accessCode.getCustomerName() != null && !accessCode.getCustomerName().isBlank()
                            ? accessCode.getCustomerName().trim() : "Customer")
                    .email(email)
                    .password(null) // passwordless — never logs in with credentials
                    .provider(AuthProvider.ACCESS_CODE)
                    .role(UserRole.CUSTOMER)
                    .emailVerified(false)
                    .createdById(resolveOrgOwnerUserIdOrNull(accessCode.getOrganization().getId()))
                    .build());
        } catch (DataIntegrityViolationException race) {
            // A concurrent redeem of the same code won the insert. The transaction is already
            // poisoned at this point, so it cannot be recovered in place — the customer retries
            // and the pre-check above signs them into the winner's account.
            log.warn("Concurrent redeem of access code {}: {}", code, race.getMostSpecificCause().getMessage());
            throw new IllegalStateException("This access code is being redeemed. Please try again.");
        }

        LocalDateTime now = LocalDateTime.now();
        if (codeRepository.consumeForUser(accessCode.getId(), customer, now) == 0) {
            throw new IllegalStateException("This access code has already been used");
        }
        accessCode.setUsedByUser(customer);
        accessCode.setUsedAt(now);

        entitlementService.onAccessCodeRedeemed(customer, accessCode.getOrganization(),
                accessCode.getValidDays(), accessCode.getProjectQuota());

        AuthResponse session = authService.buildAuthResponse(customer);
        log.info("Access code redeemed into new customer account: user={} org={} code={} quota={}",
                customer.getId(), accessCode.getOrganization().getId(), code, accessCode.getProjectQuota());
        return toRedeemResponse(session, accessCode);
    }

    /** The paint (companies + individual products) a redeemed customer was assigned. */
    @Transactional(readOnly = true)
    public AssignedProductsResponse getAssignedProducts(String customerUserId) {
        CustomerAccessCode code = codeRepository.findFirstByUsedByUserIdOrderByCreatedAtDesc(customerUserId)
                .orElseThrow(() -> new ResourceNotFoundException(
                        "No access code is linked to this account."));
        return AssignedProductsResponse.builder()
                .shopName(code.getOrganization().getName())
                .allowedBrands(code.getAllowedBrandList())
                .products(resolveProducts(code))
                .build();
    }

    private RedeemAccountResponse toRedeemResponse(AuthResponse session, CustomerAccessCode code) {
        return RedeemAccountResponse.builder()
                .accessToken(session.getAccessToken())
                .refreshToken(session.getRefreshToken())
                .tokenType(session.getTokenType())
                .expiresIn(session.getExpiresIn())
                .user(session.getUser())
                .shopName(code.getOrganization().getName())
                .validDays(code.getValidDays())
                .customerName(code.getCustomerName())
                .build();
    }

    /** AccessCodeResponse with the individually-assigned products resolved to full listings. */
    private AccessCodeResponse withAssignedProducts(CustomerAccessCode code) {
        AccessCodeResponse res = AccessCodeResponse.from(code);
        res.setAssignedProducts(resolveProducts(code));
        return res;
    }

    private List<ShopProductResponse> resolveProducts(CustomerAccessCode code) {
        List<String> ids = code.getAllowedProductIdList();
        if (ids.isEmpty()) return List.of();
        return shopProductRepository.findAllById(ids).stream()
                .map(ShopProductResponse::from)
                .toList();
    }

    /** Synthetic, unique, passwordless-account e-mail derived from the code. */
    private String customerEmailForCode(String code) {
        return "ac-" + code.toLowerCase() + "@customers.huevista.local";
    }

    private String resolveOrgOwnerUserId(String orgId) {
        return resolveOrgOwnerUserIdOptional(orgId)
                .orElseThrow(() -> new QuotaExceededException(
                        "This shop has no owner account to bill. Contact support."));
    }

    private String resolveOrgOwnerUserIdOrNull(String orgId) {
        return resolveOrgOwnerUserIdOptional(orgId).orElse(null);
    }

    private java.util.Optional<String> resolveOrgOwnerUserIdOptional(String orgId) {
        return membershipRepository.findUserIdsByOrganizationIdAndRole(orgId, OrgMemberRole.OWNER)
                .stream().findFirst();
    }

    /**
     * Redeems an access code for an ANONYMOUS guest (no account). Marks the code
     * consumed (usedAt set, usedByUser null, guestRedeemed=true) and returns a guest
     * token scoped to this code, valid until the code expires. The guest owns their
     * single image+project by this code; the issuing shop sees it via the code.
     *
     * RE-ENTRY: a code already redeemed BY A GUEST may be redeemed again while it is
     * still valid, returning a fresh token for the SAME code (and therefore the same
     * saved project). The guest's only credential is a browser cookie — a dead phone
     * or a closed incognito window used to burn the code and strand the customer at
     * the counter. The code stays scoped to one customer, per-IP redeem rate limits
     * still apply, and the validity window is unchanged. A code consumed by an
     * ACCOUNT remains strictly single-use.
     */
    @Transactional
    public GuestRedeemResponse redeemAsGuest(String code) {
        CustomerAccessCode accessCode = codeRepository.findByCode(code.toUpperCase())
                .orElseThrow(() -> new ResourceNotFoundException("Access code not found: " + code));

        if (accessCode.isRevoked()) {
            throw new IllegalStateException("This access code was cancelled by the shop");
        }
        if (accessCode.isExpired()) {
            throw new IllegalStateException("This access code has expired");
        }
        boolean reEntry = accessCode.isUsed();
        if (reEntry && (!accessCode.isGuestRedeemed() || accessCode.getUsedByUser() != null)) {
            throw new IllegalStateException("This access code has already been used");
        }

        if (!reEntry) {
            // Same compare-and-set as redeemCode: only one concurrent redeemer flips the
            // row. Losing to another GUEST redeem of this code is just the re-entry
            // case (proceed); losing to an ACCOUNT redeem must still reject — that
            // path stays strictly single-use. The re-check is a scalar query so the
            // answer comes from the database, not our stale managed entity.
            LocalDateTime now = LocalDateTime.now();
            if (codeRepository.consumeForGuest(accessCode.getId(), now) == 1) {
                accessCode.setUsedAt(now);
                accessCode.setGuestRedeemed(true);
            } else if (!codeRepository.usedByAccountUserIds(accessCode.getId()).isEmpty()) {
                throw new IllegalStateException("This access code has already been used");
            }
        }

        long ttlMs = java.time.Duration.between(LocalDateTime.now(), accessCode.getExpiresAt()).toMillis();
        String token = jwtService.generateGuestToken(accessCode.getId(), ttlMs);

        log.info("Access code redeemed by guest{}: org={} code={}",
                reEntry ? " (re-entry)" : "", accessCode.getOrganization().getId(), code);
        return GuestRedeemResponse.builder()
                .guestToken(token)
                .code(accessCode.getCode())
                .shopName(accessCode.getOrganization().getName())
                .validDays(accessCode.getValidDays())
                .expiresAt(accessCode.getExpiresAt().atZone(java.time.ZoneId.systemDefault()).toInstant())
                .allowedBrands(accessCode.getAllowedBrandList())
                .build();
    }

    /**
     * Issues a code on behalf of a retailer's public store kiosk — the caller is a
     * verified PAYMENT, not a signed-in shop member, so there is no membership check
     * here. Kiosk codes carry no brand restriction (the customer paid; they browse
     * everything). The kiosk immediately guest-redeems the code; the shop later reads
     * the real shade codes from it exactly like a counter-issued guest code.
     */
    @Transactional
    public CustomerAccessCode issueForStore(Organization org, int validDays) {
        String code = generateUniqueCode();
        CustomerAccessCode accessCode = CustomerAccessCode.builder()
                .organization(org)
                .code(code)
                .validDays(validDays)
                .expiresAt(LocalDateTime.now().plusDays(validDays))
                .build();
        accessCode = codeRepository.save(accessCode);
        log.info("Store kiosk code issued: org={} code={} validDays={}", org.getId(), code, validDays);
        return accessCode;
    }

    /** Loads a code, asserting the requester owns/manages its organization. For the
     *  shop's "view what the guest selected" lookup. */
    @Transactional(readOnly = true)
    public CustomerAccessCode requireManagedCode(String requestingUserId, String codeId) {
        CustomerAccessCode code = codeRepository.findById(codeId)
                .orElseThrow(() -> new ResourceNotFoundException("Access code not found: " + codeId));
        requireOwnerOrManager(requestingUserId, code.getOrganization().getId());
        return code;
    }

    private String generateUniqueCode() {
        String code;
        int attempts = 0;
        do {
            StringBuilder sb = new StringBuilder(CODE_LENGTH);
            for (int i = 0; i < CODE_LENGTH; i++) {
                sb.append(CODE_ALPHABET.charAt(RANDOM.nextInt(CODE_ALPHABET.length())));
            }
            code = sb.toString();
            attempts++;
            if (attempts > 10) throw new IllegalStateException("Failed to generate a unique access code");
        } while (codeRepository.existsByCode(code));
        return code;
    }

    private void requireOwnerOrManager(String userId, String orgId) {
        boolean owner = membershipRepository.existsByUserIdAndOrganizationIdAndRole(userId, orgId, OrgMemberRole.OWNER);
        boolean manager = membershipRepository.existsByUserIdAndOrganizationIdAndRole(userId, orgId, OrgMemberRole.MANAGER);
        if (!owner && !manager) {
            throw new SecurityException("Only org owners or managers can manage access codes");
        }
    }
}
