package com.gridstore.huevista.account.service;

import com.gridstore.huevista.account.dto.AccessCodeResponse;
import com.gridstore.huevista.account.dto.AssignedProductsResponse;
import com.gridstore.huevista.account.dto.GenerateAccessCodeRequest;
import com.gridstore.huevista.account.model.CustomerAccessCode;
import com.gridstore.huevista.account.model.OrgMemberRole;
import com.gridstore.huevista.account.model.OrgType;
import com.gridstore.huevista.account.model.Organization;
import com.gridstore.huevista.account.repository.CustomerAccessCodeRepository;
import com.gridstore.huevista.account.repository.OrgMembershipRepository;
import com.gridstore.huevista.account.repository.OrganizationRepository;
import com.gridstore.huevista.auth.model.User;
import com.gridstore.huevista.auth.model.UserRole;
import com.gridstore.huevista.auth.repository.UserRepository;
import com.gridstore.huevista.billing.model.Subscription;
import com.gridstore.huevista.billing.model.SubscriptionStatus;
import com.gridstore.huevista.billing.repository.SubscriptionRepository;
import com.gridstore.huevista.common.exception.QuotaExceededException;
import com.gridstore.huevista.common.exception.ResourceNotFoundException;
import com.gridstore.huevista.paint.dto.ShopProductResponse;
import com.gridstore.huevista.paint.repository.ShopProductRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.security.SecureRandom;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

@Slf4j
@Service
@RequiredArgsConstructor
public class AccessCodeService {

    private final CustomerAccessCodeRepository codeRepository;
    private final OrganizationRepository orgRepository;
    private final OrgMembershipRepository membershipRepository;
    private final UserRepository userRepository;
    private final CustomerEntitlementService entitlementService;
    private final SubscriptionRepository subscriptionRepository;
    private final com.gridstore.huevista.billing.service.BillingService billingService;
    private final com.gridstore.huevista.common.audit.AuditService auditService;
    private final BrandAccessService brandAccessService;
    private final ShopProductRepository shopProductRepository;
    private final com.gridstore.huevista.project.repository.ProjectRepository projectRepository;
    private final ProjectGrantService projectGrantService;
    private final com.gridstore.huevista.billing.service.ProjectCreditService projectCreditService;

    private static final String CODE_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"; // no ambiguous chars
    private static final int CODE_LENGTH = 8;
    private static final SecureRandom RANDOM = new SecureRandom();

    /**
     * How long an UNREDEEMED code stays redeemable. Once a customer redeems it, this
     * stops applying — their access does not expire.
     */
    private static final int UNREDEEMED_VALID_DAYS = 30;

    /** Most projects a single top-up may add to a code — a typo guard, not a policy. */
    private static final int MAX_GRANT_PROJECTS = 20;

    @Transactional
    public AccessCodeResponse generateCode(String requestingUserId, String orgId, GenerateAccessCodeRequest request) {
        Organization org = orgRepository.findById(orgId)
                .orElseThrow(() -> new ResourceNotFoundException("Organization not found: " + orgId));

        if (org.getType() != OrgType.RETAILER) {
            throw new IllegalArgumentException("Access codes can only be generated by retailer organizations");
        }

        requireOwnerOrManager(requestingUserId, orgId);

        // A shop may only hand on companies its distributor actually assigned it —
        // otherwise the whole assign/revoke feature is decorative, since a retailer could
        // unlock any brand on a code regardless of what they carry.
        brandAccessService.assertBrandsOfferable(orgId, request.getAllowedBrands());

        // Validate the individually-unlocked products actually belong to this shop, so a
        // crafted request can't unlock a competitor's listing.
        List<String> productIds = request.getAllowedProductIds();
        if (productIds != null) {
            for (String pid : productIds.stream().distinct().toList()) {
                shopProductRepository.findByIdAndOrganizationId(pid, orgId)
                        .orElseThrow(() -> new ResourceNotFoundException(
                                "Product is not one of this shop's listings: " + pid));
            }
        }

        // Charge the assigned projects against the retailer OWNER's monthly image quota
        // BEFORE creating the code — one image per assigned project, in a single atomic
        // all-or-nothing charge. If it won't fit, nothing is charged and no code exists.
        //
        // This is a PURCHASE, not a hold: nothing here is ever given back. A shop that
        // assigns three projects has spent three, whether the customer creates three
        // rooms, one, or none. That is what makes the rest of this class simple — there
        // is no reservation to track, no lock-step to keep with the subscription, and no
        // sweep to reconcile the two.
        chargeProjectQuota(orgId, request.getProjectQuota());

        String code = generateUniqueCode();

        CustomerAccessCode accessCode = CustomerAccessCode.builder()
                .organization(org)
                .code(code)
                .expiresAt(LocalDateTime.now().plusDays(UNREDEEMED_VALID_DAYS))
                .customerName(request.getCustomerName().trim())
                .projectQuota(request.getProjectQuota())
                .build();
        accessCode.setAllowedBrandList(request.getAllowedBrands());
        accessCode.setAllowedProductIdList(productIds);
        accessCode = codeRepository.save(accessCode);

        log.info("Access code generated: org={} code={} customer={} quota={} brands={} products={}",
                orgId, code, accessCode.getCustomerName(), accessCode.getProjectQuota(),
                accessCode.getAllowedBrandList(), accessCode.getAllowedProductIdList().size());
        return withAssignedProducts(accessCode);
    }

    /**
     * Charge {@code projectQuota} projects against the retailer owner's ACTIVE subscription,
     * permanently. Throws {@link QuotaExceededException} when the shop has no active plan or
     * not enough left — the retailer must buy another project from the studio or assign fewer.
     *
     * <p>The plan's own monthly allowance is not the whole of what a shop may assign: extra
     * projects it bought outright count too, and any it bought while between plans are pulled
     * onto the plan here before the second attempt. A project the shop paid for is assignable
     * wherever it happens to be sitting.
     */
    private Subscription chargeProjectQuota(String orgId, int projectQuota) {
        String ownerId = resolveOrgOwnerUserId(orgId);
        Subscription sub = subscriptionRepository
                .findEntitling(ownerId, SubscriptionStatus.ACTIVE, SubscriptionStatus.CANCELLED,
                        LocalDateTime.now())
                .stream().findFirst()
                .orElseThrow(() -> new QuotaExceededException(
                        "No active subscription. Subscribe to a plan before assigning projects to customers."));
        if (!projectCreditService.reserveIncludingBoughtExtras(ownerId, sub.getId(), projectQuota)) {
            throw new QuotaExceededException(
                    "Not enough project quota to assign " + projectQuota + " project"
                    + (projectQuota == 1 ? "" : "s") + ". Buy another project from the studio, "
                    + "upgrade your plan, or assign fewer.");
        }
        log.info("Charged {} project(s) to subscription {} for access-code assignment", projectQuota, sub.getId());
        return sub;
    }

    /**
     * Cancel a code the shop issued but nobody has redeemed yet.
     *
     * <p>Without this a mistyped customer name or a wrong project count could only be fixed
     * by issuing a SECOND code while the wrong one stayed live. A code that has already been
     * redeemed is deliberately NOT revocable: the customer's projects are theirs from the
     * moment they redeem, and taking them back afterwards is not something a counter should
     * be able to do.
     *
     * <p>Nothing is refunded. The projects on the code were bought when it was issued and
     * they are spent — cancelling only stops anyone redeeming it.
     */
    @Transactional
    public AccessCodeResponse revokeCode(String requestingUserId, String orgId, String codeId) {
        CustomerAccessCode code = requireCodeOfOrg(requestingUserId, orgId, codeId);

        if (code.isUsed()) {
            throw new IllegalStateException(
                    "This code has already been used, so it can't be cancelled. "
                    + "The projects on it belong to the customer now.");
        }
        if (codeRepository.revokeIfUnused(codeId, LocalDateTime.now()) == 0) {
            throw new IllegalStateException("This code was already cancelled or used.");
        }

        auditService.record(requestingUserId, "ACCESS_CODE_REVOKED", "ACCESS_CODE", codeId,
                "org=" + code.getOrganization().getId() + " code=" + code.getCode());
        log.info("Access code revoked: org={} code={}",
                code.getOrganization().getId(), code.getCode());
        return AccessCodeResponse.from(codeRepository.findById(codeId).orElse(code));
    }

    /**
     * Amend a code that has not been redeemed yet: the customer's name, and which
     * companies / individual products it unlocks.
     *
     * The assigned project count is deliberately NOT editable here — it is backed by held
     * image credits, and re-reserving mid-flight is a second money path for very little
     * benefit. To change the count, cancel the code (quota comes back) and issue a new one.
     */
    @Transactional
    public AccessCodeResponse updateCode(String requestingUserId, String orgId, String codeId,
                                         GenerateAccessCodeRequest request) {
        CustomerAccessCode code = requireCodeOfOrg(requestingUserId, orgId, codeId);

        if (code.isUsed()) {
            throw new IllegalStateException(
                    "This code has already been used — its assignment can no longer be changed.");
        }
        if (code.isRevoked()) {
            throw new IllegalStateException("This code was cancelled.");
        }

        brandAccessService.assertBrandsOfferable(orgId, request.getAllowedBrands());
        List<String> productIds = request.getAllowedProductIds();
        if (productIds != null) {
            for (String pid : productIds.stream().distinct().toList()) {
                shopProductRepository.findByIdAndOrganizationId(pid, orgId)
                        .orElseThrow(() -> new ResourceNotFoundException(
                                "Product is not one of this shop's listings: " + pid));
            }
        }
        code.setCustomerName(request.getCustomerName().trim());
        code.setAllowedBrandList(request.getAllowedBrands());
        code.setAllowedProductIdList(productIds);
        codeRepository.save(code);

        auditService.record(requestingUserId, "ACCESS_CODE_UPDATED", "ACCESS_CODE", codeId,
                "org=" + orgId + " code=" + code.getCode());
        log.info("Access code updated: org={} code={}", orgId, code.getCode());
        return withAssignedProducts(code);
    }

    /**
     * Add more projects to a code the shop has ALREADY issued.
     *
     * The counter case this exists for: a customer redeems a code for two rooms, then
     * decides they want the hallway done too. Before this the only answer was a second
     * code — a second set of digits for the customer to type, and the first code's
     * remaining days silently competing with the new one's. Now the shop tops up the code
     * in the customer's hand.
     *
     * Requires a LIVE subscription, for the same reason issuing a code does: each added
     * project is charged against the shop's monthly quota, and there is nothing to charge
     * without a plan. The charge is all-or-nothing, and permanent.
     *
     * Unlike {@link #updateCode} this deliberately DOES work on a redeemed code — topping
     * up the code in a customer's hand is the whole point of it.
     */
    @Transactional
    public AccessCodeResponse grantExtraProjects(String requestingUserId, String orgId,
                                                 String codeId, int projects) {
        if (projects < 1 || projects > MAX_GRANT_PROJECTS) {
            throw new IllegalArgumentException(
                    "Add between 1 and " + MAX_GRANT_PROJECTS + " projects at a time.");
        }
        CustomerAccessCode code = requireCodeOfOrg(requestingUserId, orgId, codeId);

        if (code.isRevoked()) {
            throw new IllegalStateException("This code was cancelled — issue a new one instead.");
        }
        // Only an UNREDEEMED code can run out of time, and nobody can ever redeem it now.
        if (code.isExpired()) {
            throw new IllegalStateException(
                    "Nobody redeemed this code within 30 days, so it can no longer be used. "
                    + "Issue a new one instead.");
        }
        // One lookup, not two. This used to resolve the subscription once for the gate and
        // again inside the charge, through two different queries — so the grant could be
        // recorded against a different row than the one actually charged.
        Subscription funding = chargeProjectQuota(orgId, projects);

        // Recorded for the shop's own ledger of what it has given away.
        projectGrantService.recordCodeGrant(orgId, codeId, projects, funding);

        code.setProjectQuota(code.getProjectQuota() + projects);
        codeRepository.save(code);

        // A code already redeemed into an account has an entitlement behind it; the extra
        // projects are worthless unless that allowance grows too.
        if (code.getUsedByUser() != null) {
            entitlementService.addProjectAllowance(code.getUsedByUser().getId(), projects);
        }

        auditService.record(requestingUserId, "ACCESS_CODE_PROJECTS_GRANTED", "ACCESS_CODE", codeId,
                "org=" + orgId + " code=" + code.getCode() + " added=" + projects
                        + " quota=" + code.getProjectQuota());
        log.info("Access code {} topped up with {} project(s) (quota now {})",
                code.getCode(), projects, code.getProjectQuota());
        return withProjectsUsed(code);
    }

    /** Response carrying this code's live "projects used / remaining" counters. */
    private AccessCodeResponse withProjectsUsed(CustomerAccessCode code) {
        AccessCodeResponse res = withAssignedProducts(code);
        res.applyProjectsUsed((int) projectRepository.countByAccessCodeId(code.getId()));
        return res;
    }

    @Transactional(readOnly = true)
    public List<AccessCodeResponse> listCodes(String requestingUserId, String orgId) {
        requireOwnerOrManager(requestingUserId, orgId);
        List<AccessCodeResponse> codes = codeRepository.findByOrganizationIdOrderByCreatedAtDesc(orgId).stream()
                .map(AccessCodeResponse::from)
                .toList();
        // The shop pays an image per assigned project, so the list has to show the
        // quota counting down as the customer creates rooms. One grouped query for
        // the whole page rather than a COUNT per code.
        Map<String, Long> usedByCode = countProjectsByCode(codes.stream().map(AccessCodeResponse::getId).toList());
        codes.forEach(c -> c.applyProjectsUsed(usedByCode.getOrDefault(c.getId(), 0L).intValue()));
        return codes;
    }

    /** Rooms created per access code, keyed by code id. Empty input short-circuits
     *  (JPQL rejects an empty {@code IN ()} list). */
    private Map<String, Long> countProjectsByCode(List<String> codeIds) {
        if (codeIds.isEmpty()) return Map.of();
        return projectRepository.countByAccessCodeIds(codeIds).stream()
                .collect(java.util.stream.Collectors.toMap(
                        row -> (String) row[0], row -> ((Number) row[1]).longValue()));
    }

    /**
     * Redeems an access code for an existing authenticated user.
     * Sets the user role to CUSTOMER and links them to the retailer's org.
     */
    @Transactional
    public AccessCodeResponse redeemCode(String userId, String code) {
        CustomerAccessCode accessCode = codeRepository.findByCode(code.toUpperCase())
                .orElseThrow(() -> new ResourceNotFoundException("Access code not found: " + code));

        if (accessCode.isUsed()) {
            throw new IllegalStateException("This access code has already been used");
        }
        if (accessCode.isRevoked()) {
            throw new IllegalStateException("This access code was cancelled by the shop");
        }
        if (accessCode.isExpired()) {
            throw new IllegalStateException(
                    "Nobody redeemed this code within 30 days of the shop issuing it, "
                    + "so it can no longer be used. Ask the shop for a new one.");
        }

        User user = userRepository.findById(userId)
                .orElseThrow(() -> new ResourceNotFoundException("User not found"));

        // A code may only ever be added to a CUSTOMER account. For a shop, distributor,
        // painter or admin account this would destroy their real role (and with it org
        // ownership checks, subscriptions, the admin console…). Public signups are
        // CUSTOMER already, so only customers ever legitimately redeem.
        if (user.getRole() != UserRole.CUSTOMER) {
            throw new IllegalStateException(
                    "This account is a " + String.valueOf(user.getRole()).toLowerCase()
                    + " account — access codes can only be added to a customer account. "
                    + "Ask your customer to sign in and redeem it themselves.");
        }

        // Compare-and-set consumption: if a concurrent request redeemed this code
        // between our isUsed() check and here, the guarded UPDATE matches 0 rows.
        LocalDateTime now = LocalDateTime.now();
        if (codeRepository.consumeForUser(accessCode.getId(), user, now) == 0) {
            throw new IllegalStateException("This access code has already been used");
        }

        // Mirror what the UPDATE wrote so the response (and any flush) is consistent.
        accessCode.setUsedByUser(user);
        accessCode.setUsedAt(now);

        // Open or top up the customer's project entitlement with the assigned quota.
        entitlementService.onAccessCodeRedeemed(user, accessCode.getOrganization(),
                accessCode.getProjectQuota());

        log.info("Access code redeemed: user={} org={} code={}", userId, accessCode.getOrganization().getId(), code);
        return AccessCodeResponse.from(accessCode);
    }

    /** The paint (companies + individual products) a redeemed customer was assigned. */
    @Transactional(readOnly = true)
    public AssignedProductsResponse getAssignedProducts(String customerUserId) {
        CustomerAccessCode code = codeRepository.findFirstByUsedByUserIdOrderByCreatedAtDesc(customerUserId)
                .orElseThrow(() -> new ResourceNotFoundException(
                        "No access code is linked to this account."));
        return AssignedProductsResponse.builder()
                .shopName(code.getOrganization().getName())
                .allowedBrands(code.getAllowedBrandList())
                .products(resolveProducts(code))
                .build();
    }
    /** AccessCodeResponse with the individually-assigned products resolved to full listings. */
    private AccessCodeResponse withAssignedProducts(CustomerAccessCode code) {
        AccessCodeResponse res = AccessCodeResponse.from(code);
        res.setAssignedProducts(resolveProducts(code));
        return res;
    }

    private List<ShopProductResponse> resolveProducts(CustomerAccessCode code) {
        List<String> ids = code.getAllowedProductIdList();
        if (ids.isEmpty()) return List.of();
        return shopProductRepository.findAllById(ids).stream()
                .map(ShopProductResponse::from)
                .toList();
    }

    private String resolveOrgOwnerUserId(String orgId) {
        return resolveOrgOwnerUserIdOptional(orgId)
                .orElseThrow(() -> new QuotaExceededException(
                        "This shop has no owner account to bill. Contact support."));
    }

    private String resolveOrgOwnerUserIdOrNull(String orgId) {
        return resolveOrgOwnerUserIdOptional(orgId).orElse(null);
    }

    private java.util.Optional<String> resolveOrgOwnerUserIdOptional(String orgId) {
        return membershipRepository.findUserIdsByOrganizationIdAndRole(orgId, OrgMemberRole.OWNER)
                .stream().findFirst();
    }


    /**
     * Issues a code on behalf of a retailer's public store kiosk — the caller is a
     * verified PAYMENT, not a signed-in shop member, so there is no membership check
     * here. Kiosk codes carry no brand restriction: the customer paid, so they browse
     * everything.
     *
     * <p>Marked SELF-FUNDED, which is the whole difference from a counter-issued code:
     * the walk-in bought this project at the store link, so the shop's subscription is
     * not consulted in either direction. It costs the shop no image credit (there is
     * nothing of the shop's to spend) and work under it is neither charged to the shop
     * nor gated on it — the kiosk used to take the money and only then discover the
     * SHOP's plan had lapsed, refusing work that was already paid for.
     *
     * <p>Like every other code this is redeemed onto a customer ACCOUNT. The buyer is
     * handed the code and redeems it once signed in, so a payment can never end up
     * attached to nothing.
     */
    @Transactional
    public CustomerAccessCode issueForStore(Organization org) {
        String code = generateUniqueCode();
        CustomerAccessCode accessCode = codeRepository.save(CustomerAccessCode.builder()
                .organization(org)
                .code(code)
                .expiresAt(LocalDateTime.now().plusDays(UNREDEEMED_VALID_DAYS))
                .selfFunded(true)
                .build());
        log.info("Store kiosk code issued (self-funded): org={} code={}", org.getId(), code);
        return accessCode;
    }

    /** Loads a code, asserting the requester owns/manages its organization. For the
     *  shop's "view what the guest selected" lookup. */
    @Transactional(readOnly = true)
    public CustomerAccessCode requireManagedCode(String requestingUserId, String codeId) {
        CustomerAccessCode code = codeRepository.findById(codeId)
                .orElseThrow(() -> new ResourceNotFoundException("Access code not found: " + codeId));
        requireOwnerOrManager(requestingUserId, code.getOrganization().getId());
        return code;
    }

    /**
     * Load a code and check it really belongs to the org named in the URL.
     *
     * Authorisation is on the code's OWN organization, which is what makes these
     * endpoints safe — but the {@code {orgId}} path segment was simply ignored, so
     * {@code /organizations/A/access-codes/{a-code-of-B}} authorised against B and, for a
     * member of both, quietly acted on the wrong shop's code. Not exploitable as it
     * stood; a URL that lies is a trap for the next change.
     */
    private CustomerAccessCode requireCodeOfOrg(String requestingUserId, String orgId, String codeId) {
        CustomerAccessCode code = codeRepository.findById(codeId)
                .orElseThrow(() -> new ResourceNotFoundException("Access code not found: " + codeId));
        if (!code.getOrganization().getId().equals(orgId)) {
            throw new ResourceNotFoundException("Access code not found in this shop: " + codeId);
        }
        requireOwnerOrManager(requestingUserId, orgId);
        return code;
    }

    private String generateUniqueCode() {
        String code;
        int attempts = 0;
        do {
            StringBuilder sb = new StringBuilder(CODE_LENGTH);
            for (int i = 0; i < CODE_LENGTH; i++) {
                sb.append(CODE_ALPHABET.charAt(RANDOM.nextInt(CODE_ALPHABET.length())));
            }
            code = sb.toString();
            attempts++;
            if (attempts > 10) throw new IllegalStateException("Failed to generate a unique access code");
        } while (codeRepository.existsByCode(code));
        return code;
    }

    private void requireOwnerOrManager(String userId, String orgId) {
        boolean owner = membershipRepository.existsByUserIdAndOrganizationIdAndRole(userId, orgId, OrgMemberRole.OWNER);
        boolean manager = membershipRepository.existsByUserIdAndOrganizationIdAndRole(userId, orgId, OrgMemberRole.MANAGER);
        if (!owner && !manager) {
            throw new SecurityException("Only org owners or managers can manage access codes");
        }
    }
}
