package com.gridstore.huevista.account.service;

import com.gridstore.huevista.account.dto.AccessCodeResponse;
import com.gridstore.huevista.account.dto.GenerateAccessCodeRequest;
import com.gridstore.huevista.account.dto.GuestRedeemResponse;
import com.gridstore.huevista.account.model.CustomerAccessCode;
import com.gridstore.huevista.account.model.OrgMemberRole;
import com.gridstore.huevista.account.model.OrgType;
import com.gridstore.huevista.account.model.Organization;
import com.gridstore.huevista.account.repository.CustomerAccessCodeRepository;
import com.gridstore.huevista.account.repository.OrgMembershipRepository;
import com.gridstore.huevista.account.repository.OrganizationRepository;
import com.gridstore.huevista.auth.model.User;
import com.gridstore.huevista.auth.model.UserRole;
import com.gridstore.huevista.auth.repository.UserRepository;
import com.gridstore.huevista.common.exception.ResourceNotFoundException;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.security.SecureRandom;
import java.time.LocalDateTime;
import java.util.List;

@Slf4j
@Service
@RequiredArgsConstructor
public class AccessCodeService {

    private final CustomerAccessCodeRepository codeRepository;
    private final OrganizationRepository orgRepository;
    private final OrgMembershipRepository membershipRepository;
    private final UserRepository userRepository;
    private final CustomerEntitlementService entitlementService;
    private final com.gridstore.huevista.auth.service.JwtService jwtService;

    private static final String CODE_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"; // no ambiguous chars
    private static final int CODE_LENGTH = 8;
    private static final SecureRandom RANDOM = new SecureRandom();

    @Transactional
    public AccessCodeResponse generateCode(String requestingUserId, String orgId, GenerateAccessCodeRequest request) {
        Organization org = orgRepository.findById(orgId)
                .orElseThrow(() -> new ResourceNotFoundException("Organization not found: " + orgId));

        if (org.getType() != OrgType.RETAILER) {
            throw new IllegalArgumentException("Access codes can only be generated by retailer organizations");
        }

        requireOwnerOrManager(requestingUserId, orgId);

        String code = generateUniqueCode();
        LocalDateTime expiresAt = LocalDateTime.now().plusDays(request.getValidDays());

        CustomerAccessCode accessCode = codeRepository.save(CustomerAccessCode.builder()
                .organization(org)
                .code(code)
                .validDays(request.getValidDays())
                .expiresAt(expiresAt)
                .build());

        log.info("Access code generated: org={} code={} validDays={}", orgId, code, request.getValidDays());
        return AccessCodeResponse.from(accessCode);
    }

    @Transactional(readOnly = true)
    public List<AccessCodeResponse> listCodes(String requestingUserId, String orgId) {
        requireOwnerOrManager(requestingUserId, orgId);
        return codeRepository.findByOrganizationIdOrderByCreatedAtDesc(orgId).stream()
                .map(AccessCodeResponse::from)
                .toList();
    }

    /**
     * Redeems an access code for an existing authenticated user.
     * Sets the user role to CUSTOMER and links them to the retailer's org.
     */
    @Transactional
    public AccessCodeResponse redeemCode(String userId, String code) {
        CustomerAccessCode accessCode = codeRepository.findByCode(code.toUpperCase())
                .orElseThrow(() -> new ResourceNotFoundException("Access code not found: " + code));

        if (accessCode.isUsed()) {
            throw new IllegalStateException("This access code has already been used");
        }
        if (accessCode.isExpired()) {
            throw new IllegalStateException("This access code has expired");
        }

        User user = userRepository.findById(userId)
                .orElseThrow(() -> new ResourceNotFoundException("User not found"));

        // Compare-and-set consumption: if a concurrent request redeemed this code
        // between our isUsed() check and here, the guarded UPDATE matches 0 rows.
        LocalDateTime now = LocalDateTime.now();
        if (codeRepository.consumeForUser(accessCode.getId(), user, now) == 0) {
            throw new IllegalStateException("This access code has already been used");
        }

        user.setRole(UserRole.CUSTOMER);
        userRepository.save(user);

        // Mirror what the UPDATE wrote so the response (and any flush) is consistent.
        accessCode.setUsedByUser(user);
        accessCode.setUsedAt(now);

        // Create/refresh the customer's project entitlement: 1 included project, valid for validDays.
        entitlementService.onAccessCodeRedeemed(user, accessCode.getOrganization(), accessCode.getValidDays());

        log.info("Access code redeemed: user={} org={} code={}", userId, accessCode.getOrganization().getId(), code);
        return AccessCodeResponse.from(accessCode);
    }

    /**
     * Redeems an access code for an ANONYMOUS guest (no account). Marks the code
     * consumed (usedAt set, usedByUser null, guestRedeemed=true) and returns a guest
     * token scoped to this code, valid until the code expires. The guest owns their
     * single image+project by this code; the issuing shop sees it via the code.
     */
    @Transactional
    public GuestRedeemResponse redeemAsGuest(String code) {
        CustomerAccessCode accessCode = codeRepository.findByCode(code.toUpperCase())
                .orElseThrow(() -> new ResourceNotFoundException("Access code not found: " + code));

        if (accessCode.isUsed()) {
            throw new IllegalStateException("This access code has already been used");
        }
        if (accessCode.isExpired()) {
            throw new IllegalStateException("This access code has expired");
        }

        // Same compare-and-set as redeemCode: only one concurrent redeemer can win.
        LocalDateTime now = LocalDateTime.now();
        if (codeRepository.consumeForGuest(accessCode.getId(), now) == 0) {
            throw new IllegalStateException("This access code has already been used");
        }
        accessCode.setUsedAt(now);
        accessCode.setGuestRedeemed(true);

        long ttlMs = java.time.Duration.between(LocalDateTime.now(), accessCode.getExpiresAt()).toMillis();
        String token = jwtService.generateGuestToken(accessCode.getId(), ttlMs);

        log.info("Access code redeemed by guest: org={} code={}", accessCode.getOrganization().getId(), code);
        return GuestRedeemResponse.builder()
                .guestToken(token)
                .code(accessCode.getCode())
                .shopName(accessCode.getOrganization().getName())
                .validDays(accessCode.getValidDays())
                .expiresAt(accessCode.getExpiresAt())
                .build();
    }

    /** Loads a code, asserting the requester owns/manages its organization. For the
     *  shop's "view what the guest selected" lookup. */
    @Transactional(readOnly = true)
    public CustomerAccessCode requireManagedCode(String requestingUserId, String codeId) {
        CustomerAccessCode code = codeRepository.findById(codeId)
                .orElseThrow(() -> new ResourceNotFoundException("Access code not found: " + codeId));
        requireOwnerOrManager(requestingUserId, code.getOrganization().getId());
        return code;
    }

    private String generateUniqueCode() {
        String code;
        int attempts = 0;
        do {
            StringBuilder sb = new StringBuilder(CODE_LENGTH);
            for (int i = 0; i < CODE_LENGTH; i++) {
                sb.append(CODE_ALPHABET.charAt(RANDOM.nextInt(CODE_ALPHABET.length())));
            }
            code = sb.toString();
            attempts++;
            if (attempts > 10) throw new IllegalStateException("Failed to generate a unique access code");
        } while (codeRepository.existsByCode(code));
        return code;
    }

    private void requireOwnerOrManager(String userId, String orgId) {
        boolean owner = membershipRepository.existsByUserIdAndOrganizationIdAndRole(userId, orgId, OrgMemberRole.OWNER);
        boolean manager = membershipRepository.existsByUserIdAndOrganizationIdAndRole(userId, orgId, OrgMemberRole.MANAGER);
        if (!owner && !manager) {
            throw new SecurityException("Only org owners or managers can manage access codes");
        }
    }
}
