package com.gridstore.huevista.project.service;

import jakarta.annotation.PostConstruct;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import javax.imageio.ImageIO;
import java.awt.Color;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.IOException;

/**
 * TESTING ONLY — replaces the two paid Replicate steps of the segmentation
 * pipeline with local no-ops, so the whole upload → project → recolour → share
 * flow can be exercised end to end without spending a rupee on image models.
 *
 * <p>When {@code huevista.testing.stub-ai.enabled=true}:
 * <ul>
 *   <li>{@link ImageCleanerService} is skipped entirely — the photo is NOT
 *       cleaned or repainted, and the project keeps the original upload as its
 *       canvas ({@code cleanedImageStorageKey} stays null, so the frontend
 *       renders the untouched photo). The Claude-powered
 *       {@link CleaningHintService} never runs either, because it is only
 *       reachable from inside the cleaner.</li>
 *   <li>{@link ReplicateMaskSegmenter} is skipped — the colour-coded mask is
 *       drawn locally by {@link #colorCodedMask} instead of generated by
 *       FLUX.2 / Nano Banana.</li>
 * </ul>
 *
 * <p><b>Claude is deliberately left alone.</b> The upload-time
 * {@link com.gridstore.huevista.image.service.ClaudeVisionService} check —
 * "is this an indoor room, a house exterior, or not a house at all?" — still
 * calls the real API, so image validation and the INDOOR/OUTDOOR branch stay
 * honest under test. Only the image-GENERATION vendors are stubbed.
 *
 * <p>Billing is untouched: a stub run charges credits exactly like a real one,
 * so plan limits, held credits and quota errors remain testable.
 *
 * <p>Default false, and never to be enabled in production — a stub run
 * produces masks that have nothing to do with the photo.
 */
@Slf4j
@Service
public class StubAiPipeline {

    @Value("${huevista.testing.stub-ai.enabled:false}")
    private boolean enabled;

    public boolean isEnabled() {
        return enabled;
    }

    /** Loud startup banner — this flag must never be left on by accident. */
    @PostConstruct
    void warnWhenEnabled() {
        if (enabled) {
            log.warn("=================================================================");
            log.warn(" STUB AI PIPELINE IS ENABLED (huevista.testing.stub-ai.enabled)");
            log.warn(" Photos will NOT be cleaned and masks are FAKE vertical stripes.");
            log.warn(" Claude image classification still runs. TESTING ONLY —");
            log.warn(" never enable this in production.");
            log.warn("=================================================================");
        }
    }

    /**
     * Draws the fake colour-coded mask the real mask model would have returned:
     * three equal vertical stripes across the full height of the canvas.
     *
     * <pre>
     *   +-----------+-----------+-----------+
     *   |    RED    |   GREEN   |   BLUE    |
     *   |  #FF0000  |  #00FF00  |  #0000FF  |
     *   |   main    |  accent   |   trim    |
     *   |   wall    |   wall    | &amp; frames  |
     *   +-----------+-----------+-----------+
     * </pre>
     *
     * The three colours are exactly the palette
     * {@link MaskProcessor#splitColorCodedMask} expects, so the split produces
     * all three regions on every run — main, accent and trim — and each is far
     * above the noise thresholds. That gives every downstream feature something
     * to work with: three recolourable regions, the region list, per-region
     * shade picking, the compare slider, PDF export and sharing.
     *
     * <p>Deliberately deterministic rather than randomised: a fixed layout means
     * a mask that lands in the wrong place is a real bug, not this stub rolling
     * a different shape. Stripes are vertical so each one spans floor-to-ceiling
     * and no region can be mistaken for the sky filter's top band.
     *
     * <p>Rendered at the canvas's own width and height, so the caller's
     * resize-to-canvas step is a no-op and no aspect drift is introduced.
     *
     * @param width  canvas width in pixels (≥ 3)
     * @param height canvas height in pixels (≥ 1)
     */
    byte[] colorCodedMask(int width, int height) throws IOException {
        int w = Math.max(3, width);
        int h = Math.max(1, height);

        BufferedImage img = new BufferedImage(w, h, BufferedImage.TYPE_INT_RGB);
        // Integer stripe boundaries: the last stripe absorbs the remainder so
        // the three together always cover the full width with no unpainted
        // column (which would otherwise read as an unassigned black seam).
        int firstEnd = w / 3;
        int secondEnd = (2 * w) / 3;
        for (int x = 0; x < w; x++) {
            int rgb = (x < firstEnd ? Color.RED
                     : x < secondEnd ? Color.GREEN
                     : Color.BLUE).getRGB();
            for (int y = 0; y < h; y++) {
                img.setRGB(x, y, rgb);
            }
        }

        ByteArrayOutputStream out = new ByteArrayOutputStream();
        if (!ImageIO.write(img, "png", out)) {
            throw new IOException("PNG encoder not available for stub mask");
        }
        log.info("Stub AI pipeline: generated fake {}x{} colour-coded mask " +
                "(vertical RED|GREEN|BLUE thirds) — no Replicate call made", w, h);
        return out.toByteArray();
    }
}
