-- Distributor → retailer brand assignments.
--
-- A distributor stocks certain paint companies (Asian Paints, Berger, …) and
-- decides which of them each of its shops may work with. Each row grants one
-- brand to one retailer shop, recording the distributor that granted it.
--
-- A shop with no rows is treated as "all brands" by the application layer, so
-- existing shops keep their current (unrestricted) behaviour until a
-- distributor makes an explicit selection.

CREATE TABLE retailer_brand_assignments (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    distributor_id character varying(255) NOT NULL,
    retailer_id character varying(255) NOT NULL,
    brand_id bigint NOT NULL,
    assigned_at timestamp(6) without time zone
);

ALTER TABLE ONLY retailer_brand_assignments
    ADD CONSTRAINT retailer_brand_assignments_pkey PRIMARY KEY (id);
ALTER TABLE ONLY retailer_brand_assignments
    ADD CONSTRAINT uq_retailer_brand UNIQUE (retailer_id, brand_id);
ALTER TABLE ONLY retailer_brand_assignments
    ADD CONSTRAINT fk_rba_distributor FOREIGN KEY (distributor_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE ONLY retailer_brand_assignments
    ADD CONSTRAINT fk_rba_retailer FOREIGN KEY (retailer_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE ONLY retailer_brand_assignments
    ADD CONSTRAINT fk_rba_brand FOREIGN KEY (brand_id) REFERENCES brands(id) ON DELETE CASCADE;

CREATE INDEX idx_rba_retailer ON retailer_brand_assignments (retailer_id);
CREATE INDEX idx_rba_distributor ON retailer_brand_assignments (distributor_id);
