-- ============================================================================
-- V1  Baseline schema
-- ----------------------------------------------------------------------------
-- Generated from the JPA entities via Hibernate (ddl-auto=update) against
-- PostgreSQL 16, then captured with pg_dump --schema-only. This is the schema
-- the application ran on before Flyway was introduced.
--
-- Databases that already exist (created by the old ddl-auto=update) are stamped
-- with baseline-version=1 by spring.flyway.baseline-on-migrate and SKIP this
-- file; only fresh, empty databases execute it. All future schema changes go in
-- new versioned files (V2__..., V3__...) - never edit this one.
-- ============================================================================

CREATE TABLE audit_logs (
    id bigint NOT NULL,
    action character varying(255) NOT NULL,
    actor_user_id character varying(255),
    created_at timestamp(6) without time zone,
    detail text,
    target_id character varying(255),
    target_type character varying(255)
);

ALTER TABLE audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE brands (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    slug character varying(255) NOT NULL
);

ALTER TABLE brands ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME brands_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE customer_access_codes (
    id character varying(255) NOT NULL,
    allowed_brands character varying(512),
    code character varying(8) NOT NULL,
    created_at timestamp(6) without time zone,
    expires_at timestamp(6) without time zone NOT NULL,
    guest_redeemed boolean DEFAULT false NOT NULL,
    used_at timestamp(6) without time zone,
    valid_days integer NOT NULL,
    organization_id character varying(255) NOT NULL,
    used_by_user_id character varying(255)
);

CREATE TABLE customer_entitlements (
    id character varying(255) NOT NULL,
    access_expires_at timestamp(6) without time zone NOT NULL,
    created_at timestamp(6) without time zone,
    project_allowance integer NOT NULL,
    projects_created integer NOT NULL,
    updated_at timestamp(6) without time zone,
    version bigint DEFAULT 0 NOT NULL,
    customer_user_id character varying(255) NOT NULL,
    retailer_org_id character varying(255)
);

CREATE TABLE distributor_retailer_links (
    id bigint NOT NULL,
    commission_rate_override numeric(5,2),
    linked_at timestamp(6) without time zone,
    distributor_id character varying(255) NOT NULL,
    retailer_id character varying(255) NOT NULL
);

ALTER TABLE distributor_retailer_links ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME distributor_retailer_links_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE org_memberships (
    id bigint NOT NULL,
    joined_at timestamp(6) without time zone,
    role character varying(255) NOT NULL,
    organization_id character varying(255) NOT NULL,
    user_id character varying(255) NOT NULL,
    CONSTRAINT org_memberships_role_check CHECK (((role)::text = ANY ((ARRAY['OWNER'::character varying, 'MANAGER'::character varying, 'STAFF'::character varying])::text[])))
);

ALTER TABLE org_memberships ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME org_memberships_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE organizations (
    id character varying(255) NOT NULL,
    city character varying(255),
    commission_rate numeric(5,2),
    created_at timestamp(6) without time zone,
    name character varying(255) NOT NULL,
    slug character varying(255) NOT NULL,
    state character varying(255),
    subdomain_slug character varying(255),
    type character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    whitelabel_enabled boolean NOT NULL,
    owner_user_id character varying(255) NOT NULL,
    CONSTRAINT organizations_type_check CHECK (((type)::text = ANY ((ARRAY['DISTRIBUTOR'::character varying, 'RETAILER'::character varying])::text[])))
);

CREATE TABLE paint_jobs (
    id character varying(255) NOT NULL,
    completed_at timestamp(6) without time zone,
    created_at timestamp(6) without time zone,
    decline_reason text,
    estimated_area_sqft numeric(10,2),
    estimated_days integer,
    estimated_paint_liters numeric(10,2),
    notes text,
    quoted_amount_inr numeric(10,2),
    scheduled_for timestamp(6) without time zone,
    site_address text,
    started_at timestamp(6) without time zone,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    customer_id character varying(255) NOT NULL,
    painter_id character varying(255),
    project_id character varying(255) NOT NULL,
    retailer_id character varying(255) NOT NULL,
    CONSTRAINT paint_jobs_status_check CHECK (((status)::text = ANY ((ARRAY['NEW'::character varying, 'ACCEPTED'::character varying, 'DECLINED'::character varying, 'IN_PROGRESS'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])))
);

CREATE TABLE paint_lines (
    id bigint NOT NULL,
    category character varying(255) NOT NULL,
    default_finish character varying(255),
    name character varying(255) NOT NULL,
    quality_tier character varying(255),
    brand_id bigint NOT NULL,
    CONSTRAINT paint_lines_category_check CHECK (((category)::text = ANY ((ARRAY['INTERIOR'::character varying, 'EXTERIOR'::character varying])::text[]))),
    CONSTRAINT paint_lines_quality_tier_check CHECK (((quality_tier)::text = ANY ((ARRAY['ECONOMY'::character varying, 'PREMIUM'::character varying, 'LUXURY'::character varying])::text[])))
);

ALTER TABLE paint_lines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME paint_lines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE painter_invitations (
    id character varying(255) NOT NULL,
    code character varying(16) NOT NULL,
    created_at timestamp(6) without time zone,
    expires_at timestamp(6) without time zone NOT NULL,
    phone_hint character varying(255),
    used_at timestamp(6) without time zone,
    retailer_id character varying(255) NOT NULL,
    used_by_painter_id character varying(255)
);

CREATE TABLE painter_profiles (
    user_id character varying(255) NOT NULL,
    active boolean NOT NULL,
    created_at timestamp(6) without time zone,
    day_rate_inr numeric(10,2),
    jobs_completed integer NOT NULL,
    phone character varying(255),
    rating numeric(3,2),
    service_areas text,
    specialties text,
    updated_at timestamp(6) without time zone,
    years_experience integer
);

CREATE TABLE painter_retailer_links (
    id character varying(255) NOT NULL,
    accepted_at timestamp(6) without time zone,
    commission_pct numeric(5,2),
    created_at timestamp(6) without time zone,
    invited_at timestamp(6) without time zone,
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    painter_id character varying(255) NOT NULL,
    retailer_id character varying(255) NOT NULL,
    CONSTRAINT painter_retailer_links_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'ACTIVE'::character varying, 'INACTIVE'::character varying, 'REMOVED'::character varying])::text[])))
);

CREATE TABLE password_reset_codes (
    id bigint NOT NULL,
    attempts integer NOT NULL,
    code_hash character varying(255) NOT NULL,
    consumed boolean NOT NULL,
    created_at timestamp(6) without time zone,
    expires_at timestamp(6) without time zone NOT NULL,
    user_id character varying(255) NOT NULL
);

ALTER TABLE password_reset_codes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME password_reset_codes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE processed_webhook_events (
    event_id character varying(64) NOT NULL,
    processed_at timestamp(6) without time zone
);

CREATE TABLE project_credit_payments (
    id character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    order_id character varying(255) NOT NULL,
    payment_id character varying(255) NOT NULL,
    user_id character varying(255) NOT NULL
);

CREATE TABLE projects (
    id character varying(255) NOT NULL,
    cleaned_image_storage_key character varying(255),
    created_at timestamp(6) without time zone,
    failure_reason text,
    name character varying(255) NOT NULL,
    notes text,
    replicate_prediction_id character varying(255),
    room_type character varying(255),
    share_expires_at timestamp(6) without time zone,
    share_token character varying(255),
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    access_code_id character varying(255),
    image_id character varying(255) NOT NULL,
    user_id character varying(255),
    CONSTRAINT projects_status_check CHECK (((status)::text = ANY ((ARRAY['CREATED'::character varying, 'SEGMENTING'::character varying, 'SEGMENTED'::character varying, 'FAILED'::character varying])::text[])))
);

CREATE TABLE refresh_tokens (
    id character varying(255) NOT NULL,
    expiry_date timestamp(6) with time zone NOT NULL,
    token character varying(64) NOT NULL,
    used_at timestamp(6) with time zone,
    user_id character varying(255) NOT NULL
);

CREATE TABLE regions (
    id bigint NOT NULL,
    applied_hex_code character varying(255),
    applied_shade_code character varying(255),
    category character varying(255),
    created_at timestamp(6) without time zone,
    display_order integer,
    label character varying(255),
    manual boolean NOT NULL,
    mask_data text,
    mask_url character varying(2048),
    project_id character varying(255) NOT NULL,
    CONSTRAINT regions_category_check CHECK (((category)::text = ANY ((ARRAY['MAIN_WALL'::character varying, 'ACCENT_WALL'::character varying, 'OTHER_WALL'::character varying, 'TRIM'::character varying, 'MANUAL'::character varying])::text[])))
);

ALTER TABLE regions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME regions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE shades (
    id bigint NOT NULL,
    ai_description text,
    color_temperature character varying(255),
    created_at timestamp(6) without time zone,
    feature_tag character varying(255),
    finish_recommendations text,
    hex_code character varying(7) NOT NULL,
    lrv numeric(5,2),
    mood_descriptors text,
    name character varying(255) NOT NULL,
    page_url character varying(500),
    popularity integer,
    rgbb integer,
    rgbg integer,
    rgbr integer,
    shade_code character varying(255) NOT NULL,
    shade_family character varying(255),
    style_tags text,
    suitable_rooms text,
    tonality character varying(255),
    brand_id bigint NOT NULL
);

ALTER TABLE shades ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME shades_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE shop_products (
    id character varying(255) NOT NULL,
    brightness integer,
    coverage character varying(255),
    created_at timestamp(6) without time zone,
    description text,
    features text,
    finish character varying(255),
    image_url character varying(255),
    pack_size character varying(255),
    price numeric(10,2),
    price_unit character varying(255),
    quality_tier character varying(255),
    updated_at timestamp(6) without time zone,
    paint_line_id bigint NOT NULL,
    organization_id character varying(255) NOT NULL,
    CONSTRAINT shop_products_quality_tier_check CHECK (((quality_tier)::text = ANY ((ARRAY['ECONOMY'::character varying, 'PREMIUM'::character varying, 'LUXURY'::character varying])::text[])))
);

CREATE TABLE subscriptions (
    id character varying(255) NOT NULL,
    ai_generations_limit integer NOT NULL,
    ai_generations_used integer NOT NULL,
    cancel_at_period_end boolean NOT NULL,
    created_at timestamp(6) without time zone,
    current_period_end timestamp(6) without time zone,
    current_period_start timestamp(6) without time zone,
    plan character varying(255) NOT NULL,
    razorpay_customer_id character varying(255),
    razorpay_subscription_id character varying(255),
    status character varying(255) NOT NULL,
    trial boolean DEFAULT false NOT NULL,
    updated_at timestamp(6) without time zone,
    user_id character varying(255) NOT NULL,
    CONSTRAINT subscriptions_plan_check CHECK (((plan)::text = ANY ((ARRAY['STARTER'::character varying, 'PROFESSIONAL'::character varying, 'BUSINESS'::character varying, 'ENTERPRISE'::character varying])::text[]))),
    CONSTRAINT subscriptions_status_check CHECK (((status)::text = ANY ((ARRAY['CREATED'::character varying, 'ACTIVE'::character varying, 'HALTED'::character varying, 'CANCELLED'::character varying, 'COMPLETED'::character varying, 'EXPIRED'::character varying])::text[])))
);

CREATE TABLE support_conversations (
    id character varying(255) NOT NULL,
    channel character varying(255) NOT NULL,
    contact_channel_id character varying(255),
    contact_name character varying(255),
    created_at timestamp(6) without time zone,
    status character varying(255) NOT NULL,
    subject character varying(255),
    updated_at timestamp(6) without time zone,
    assignee_user_id character varying(255),
    user_id character varying(255),
    CONSTRAINT support_conversations_channel_check CHECK (((channel)::text = ANY ((ARRAY['IN_APP'::character varying, 'WHATSAPP'::character varying, 'VOICE'::character varying, 'EMAIL'::character varying])::text[]))),
    CONSTRAINT support_conversations_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'NEEDS_HUMAN'::character varying, 'RESOLVED'::character varying])::text[])))
);

CREATE TABLE support_messages (
    id character varying(255) NOT NULL,
    body text NOT NULL,
    created_at timestamp(6) without time zone,
    sender character varying(255) NOT NULL,
    conversation_id character varying(255) NOT NULL,
    CONSTRAINT support_messages_sender_check CHECK (((sender)::text = ANY ((ARRAY['USER'::character varying, 'AI'::character varying, 'AGENT'::character varying, 'SYSTEM'::character varying])::text[])))
);

CREATE TABLE uploaded_images (
    id character varying(255) NOT NULL,
    content_type character varying(255) NOT NULL,
    file_size bigint NOT NULL,
    height integer,
    image_type character varying(255) NOT NULL,
    original_filename character varying(255) NOT NULL,
    storage_key character varying(255) NOT NULL,
    uploaded_at timestamp(6) without time zone,
    width integer,
    access_code_id character varying(255),
    user_id character varying(255),
    CONSTRAINT uploaded_images_image_type_check CHECK (((image_type)::text = ANY ((ARRAY['INDOOR'::character varying, 'OUTDOOR'::character varying, 'UNKNOWN'::character varying])::text[])))
);

CREATE TABLE users (
    id character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    deleted_at timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    email_verified boolean NOT NULL,
    failed_login_attempts integer DEFAULT 0 NOT NULL,
    locked_until timestamp(6) without time zone,
    name character varying(255) NOT NULL,
    password character varying(255),
    phone_number character varying(255),
    phone_verified boolean DEFAULT false NOT NULL,
    picture character varying(255),
    provider character varying(255) NOT NULL,
    provider_id character varying(255),
    role character varying(255) DEFAULT 'RETAILER'::character varying NOT NULL,
    updated_at timestamp(6) without time zone,
    CONSTRAINT users_provider_check CHECK (((provider)::text = ANY ((ARRAY['LOCAL'::character varying, 'GOOGLE'::character varying])::text[]))),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'DISTRIBUTOR'::character varying, 'RETAILER'::character varying, 'PAINTER'::character varying, 'CUSTOMER'::character varying])::text[])))
);

CREATE TABLE verification_codes (
    id bigint NOT NULL,
    attempts integer NOT NULL,
    channel character varying(255) NOT NULL,
    code_hash character varying(255) NOT NULL,
    consumed boolean NOT NULL,
    created_at timestamp(6) without time zone,
    destination character varying(255) NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    user_id character varying(255) NOT NULL,
    CONSTRAINT verification_codes_channel_check CHECK (((channel)::text = ANY ((ARRAY['EMAIL'::character varying, 'PHONE'::character varying])::text[])))
);

ALTER TABLE verification_codes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME verification_codes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY audit_logs
    ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY brands
    ADD CONSTRAINT brands_pkey PRIMARY KEY (id);

ALTER TABLE ONLY customer_access_codes
    ADD CONSTRAINT customer_access_codes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY customer_entitlements
    ADD CONSTRAINT customer_entitlements_pkey PRIMARY KEY (id);

ALTER TABLE ONLY distributor_retailer_links
    ADD CONSTRAINT distributor_retailer_links_pkey PRIMARY KEY (id);

ALTER TABLE ONLY org_memberships
    ADD CONSTRAINT org_memberships_pkey PRIMARY KEY (id);

ALTER TABLE ONLY organizations
    ADD CONSTRAINT organizations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY paint_jobs
    ADD CONSTRAINT paint_jobs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY paint_lines
    ADD CONSTRAINT paint_lines_pkey PRIMARY KEY (id);

ALTER TABLE ONLY painter_invitations
    ADD CONSTRAINT painter_invitations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY painter_profiles
    ADD CONSTRAINT painter_profiles_pkey PRIMARY KEY (user_id);

ALTER TABLE ONLY painter_retailer_links
    ADD CONSTRAINT painter_retailer_links_pkey PRIMARY KEY (id);

ALTER TABLE ONLY password_reset_codes
    ADD CONSTRAINT password_reset_codes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY processed_webhook_events
    ADD CONSTRAINT processed_webhook_events_pkey PRIMARY KEY (event_id);

ALTER TABLE ONLY project_credit_payments
    ADD CONSTRAINT project_credit_payments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY projects
    ADD CONSTRAINT projects_pkey PRIMARY KEY (id);

ALTER TABLE ONLY refresh_tokens
    ADD CONSTRAINT refresh_tokens_pkey PRIMARY KEY (id);

ALTER TABLE ONLY regions
    ADD CONSTRAINT regions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY shades
    ADD CONSTRAINT shades_pkey PRIMARY KEY (id);

ALTER TABLE ONLY shop_products
    ADD CONSTRAINT shop_products_pkey PRIMARY KEY (id);

ALTER TABLE ONLY subscriptions
    ADD CONSTRAINT subscriptions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY support_conversations
    ADD CONSTRAINT support_conversations_pkey PRIMARY KEY (id);

ALTER TABLE ONLY support_messages
    ADD CONSTRAINT support_messages_pkey PRIMARY KEY (id);

ALTER TABLE ONLY subscriptions
    ADD CONSTRAINT uk1yt5go8ygu2idlvc54weod8lo UNIQUE (razorpay_subscription_id);

ALTER TABLE ONLY painter_retailer_links
    ADD CONSTRAINT uk2l7w56h5xq184vlbhn7weiq68 UNIQUE (painter_id, retailer_id);

ALTER TABLE ONLY shades
    ADD CONSTRAINT uk4g707b56jqynofolh06yqns1e UNIQUE (brand_id, shade_code);

ALTER TABLE ONLY paint_lines
    ADD CONSTRAINT uk50xm65526r1lbqy8ccr77scqx UNIQUE (brand_id, category, name);

ALTER TABLE ONLY users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);

ALTER TABLE ONLY customer_access_codes
    ADD CONSTRAINT uk8uw52cjnajtijb67so6p9gm3s UNIQUE (code);

ALTER TABLE ONLY org_memberships
    ADD CONSTRAINT uk9myyukc8hub1slyuqe177xll9 UNIQUE (user_id, organization_id);

ALTER TABLE ONLY painter_invitations
    ADD CONSTRAINT ukaql2fqp7qanpx1yvfcktb0p7u UNIQUE (code);

ALTER TABLE ONLY distributor_retailer_links
    ADD CONSTRAINT ukck6c44eks0r59h5nmuq0lnl7g UNIQUE (distributor_id, retailer_id);

ALTER TABLE ONLY projects
    ADD CONSTRAINT ukdxrwbgbn7v5gotfeo2r12fw43 UNIQUE (share_token);

ALTER TABLE ONLY customer_entitlements
    ADD CONSTRAINT ukf5v1tv0rftk7bwwbd3d0fbi2d UNIQUE (customer_user_id);

ALTER TABLE ONLY refresh_tokens
    ADD CONSTRAINT ukghpmfn23vmxfu3spu3lfg4r2d UNIQUE (token);

ALTER TABLE ONLY organizations
    ADD CONSTRAINT ukktinpvkdjn4ljfctbfnvfmqvk UNIQUE (subdomain_slug);

ALTER TABLE ONLY brands
    ADD CONSTRAINT ukoce3937d2f4mpfqrycbr0l93m UNIQUE (name);

ALTER TABLE ONLY brands
    ADD CONSTRAINT ukpnhnc9urm6fro7oseu9vka70q UNIQUE (slug);

ALTER TABLE ONLY project_credit_payments
    ADD CONSTRAINT uksd7ct7og2ehdahtr8qcjtnpjp UNIQUE (payment_id);

ALTER TABLE ONLY organizations
    ADD CONSTRAINT uksfr9257mbjkowos3ci3e22ay2 UNIQUE (slug);

ALTER TABLE ONLY uploaded_images
    ADD CONSTRAINT uploaded_images_pkey PRIMARY KEY (id);

ALTER TABLE ONLY users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY verification_codes
    ADD CONSTRAINT verification_codes_pkey PRIMARY KEY (id);

CREATE INDEX idx_audit_action ON audit_logs USING btree (action);

CREATE INDEX idx_audit_actor ON audit_logs USING btree (actor_user_id);

CREATE INDEX idx_pwreset_user ON password_reset_codes USING btree (user_id);

CREATE INDEX idx_shades_brand_id ON shades USING btree (brand_id);

CREATE INDEX idx_shades_popularity ON shades USING btree (popularity);

CREATE INDEX idx_shades_shade_family ON shades USING btree (shade_family);

CREATE INDEX idx_vcode_user_channel ON verification_codes USING btree (user_id, channel);

ALTER TABLE ONLY refresh_tokens
    ADD CONSTRAINT fk1lih5y2npsf8u5o3vhdb9y0os FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ONLY shop_products
    ADD CONSTRAINT fk2xbpejw9leenctyajt8ogp8ef FOREIGN KEY (paint_line_id) REFERENCES paint_lines(id);

ALTER TABLE ONLY organizations
    ADD CONSTRAINT fk37dv86ymr1mh8lhcosssu5rc6 FOREIGN KEY (owner_user_id) REFERENCES users(id);

ALTER TABLE ONLY projects
    ADD CONSTRAINT fk3ap2wq1kk8b3l0wnehs1df530 FOREIGN KEY (access_code_id) REFERENCES customer_access_codes(id);

ALTER TABLE ONLY shades
    ADD CONSTRAINT fk4ca0250gipamsh57h9qm1tkib FOREIGN KEY (brand_id) REFERENCES brands(id);

ALTER TABLE ONLY support_conversations
    ADD CONSTRAINT fk4mwpr1plkjvoc7wxviqf6vs6v FOREIGN KEY (assignee_user_id) REFERENCES users(id);

ALTER TABLE ONLY uploaded_images
    ADD CONSTRAINT fk4unx6aqchm3xp5rg0id79lcyb FOREIGN KEY (access_code_id) REFERENCES customer_access_codes(id);

ALTER TABLE ONLY projects
    ADD CONSTRAINT fk5ih054rvt5le4mvcbg7aas8v7 FOREIGN KEY (image_id) REFERENCES uploaded_images(id);

ALTER TABLE ONLY painter_invitations
    ADD CONSTRAINT fk5k0drfyaqw6pvw87gvfxwn9pm FOREIGN KEY (used_by_painter_id) REFERENCES users(id);

ALTER TABLE ONLY uploaded_images
    ADD CONSTRAINT fk7cet152e6aqgt57a7k5f0rjne FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ONLY distributor_retailer_links
    ADD CONSTRAINT fk7rnx64alv4u6b65y7nmbcp8qp FOREIGN KEY (distributor_id) REFERENCES organizations(id);

ALTER TABLE ONLY customer_entitlements
    ADD CONSTRAINT fk7wr9rl0bgtwgcqy6hkkpxqi7i FOREIGN KEY (retailer_org_id) REFERENCES organizations(id);

ALTER TABLE ONLY painter_retailer_links
    ADD CONSTRAINT fk9h961066axxb5f3ahwdssa41d FOREIGN KEY (painter_id) REFERENCES users(id);

ALTER TABLE ONLY customer_access_codes
    ADD CONSTRAINT fk9lob7vme9durlxyok6uqp8y7a FOREIGN KEY (used_by_user_id) REFERENCES users(id);

ALTER TABLE ONLY painter_retailer_links
    ADD CONSTRAINT fk9wws9ak6jpsbinqrhc7a0fuyi FOREIGN KEY (retailer_id) REFERENCES organizations(id);

ALTER TABLE ONLY paint_jobs
    ADD CONSTRAINT fka8npdlihefxksss0rata9ppae FOREIGN KEY (project_id) REFERENCES projects(id);

ALTER TABLE ONLY distributor_retailer_links
    ADD CONSTRAINT fkaravpxih8nmygkjxo52op2l7v FOREIGN KEY (retailer_id) REFERENCES organizations(id);

ALTER TABLE ONLY customer_access_codes
    ADD CONSTRAINT fkbgb5ajeaojgmna8rprkg2ngxd FOREIGN KEY (organization_id) REFERENCES organizations(id);

ALTER TABLE ONLY paint_jobs
    ADD CONSTRAINT fkd7u44vewl0jj6cm6653h6kaix FOREIGN KEY (retailer_id) REFERENCES organizations(id);

ALTER TABLE ONLY subscriptions
    ADD CONSTRAINT fkhro52ohfqfbay9774bev0qinr FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ONLY projects
    ADD CONSTRAINT fkhswfwa3ga88vxv1pmboss6jhm FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ONLY support_conversations
    ADD CONSTRAINT fkjc4dm2jeajdrl1rk5u1cis7m5 FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ONLY regions
    ADD CONSTRAINT fkl13bjr0rt80nv4en2e4sd6cf0 FOREIGN KEY (project_id) REFERENCES projects(id);

ALTER TABLE ONLY paint_lines
    ADD CONSTRAINT fklj5b8glgfw5bkqj2no6merrmj FOREIGN KEY (brand_id) REFERENCES brands(id);

ALTER TABLE ONLY customer_entitlements
    ADD CONSTRAINT fkltwqc3g2cd2l4uv5a5k3c6l2e FOREIGN KEY (customer_user_id) REFERENCES users(id);

ALTER TABLE ONLY support_messages
    ADD CONSTRAINT fkmnjbe8u4i9wt1eyo43px15nvc FOREIGN KEY (conversation_id) REFERENCES support_conversations(id);

ALTER TABLE ONLY org_memberships
    ADD CONSTRAINT fkmole0m39ex6cyrjlfimr659t8 FOREIGN KEY (user_id) REFERENCES users(id);

ALTER TABLE ONLY paint_jobs
    ADD CONSTRAINT fknais5ni80o1dakob1gdis6x6b FOREIGN KEY (customer_id) REFERENCES users(id);

ALTER TABLE ONLY org_memberships
    ADD CONSTRAINT fkouk10ep5kfd1gyng0n3mxvv1y FOREIGN KEY (organization_id) REFERENCES organizations(id);

ALTER TABLE ONLY painter_invitations
    ADD CONSTRAINT fkpidu9ls98waimnftflfld2pko FOREIGN KEY (retailer_id) REFERENCES organizations(id);

ALTER TABLE ONLY shop_products
    ADD CONSTRAINT fkq1hrpdxs1i9373txyo15ki3s9 FOREIGN KEY (organization_id) REFERENCES organizations(id);

ALTER TABLE ONLY paint_jobs
    ADD CONSTRAINT fks687d8veu61mgqkssunghnd3e FOREIGN KEY (painter_id) REFERENCES users(id);

ALTER TABLE ONLY painter_profiles
    ADD CONSTRAINT fkt9spwed5vokrns2ys71411k29 FOREIGN KEY (user_id) REFERENCES users(id);
