-- Distributor → retailer page (feature) assignments.
--
-- The sibling of V19's brand assignments: a distributor already decides which
-- paint companies each of its shops may work with, and now also decides which
-- parts of the product each shop may open — Studio, Colour finder, Catalogue,
-- Products, Customer portal, My network. Each row switches one page on for one
-- shop, recording the distributor that granted it.
--
-- Whether a shop is limited at all lives in organizations.features_restricted,
-- not in the row count, for the same reason brands_restricted exists: zero rows
-- cannot distinguish "not configured yet" from "every page revoked". The column
-- defaults to false, so every existing shop keeps its current full access until
-- a distributor makes an explicit selection.

ALTER TABLE organizations
    ADD COLUMN features_restricted boolean DEFAULT false NOT NULL;

CREATE TABLE retailer_feature_assignments (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    distributor_id character varying(255) NOT NULL,
    retailer_id character varying(255) NOT NULL,
    feature character varying(64) NOT NULL,
    assigned_at timestamp(6) without time zone
);

ALTER TABLE ONLY retailer_feature_assignments
    ADD CONSTRAINT retailer_feature_assignments_pkey PRIMARY KEY (id);
ALTER TABLE ONLY retailer_feature_assignments
    ADD CONSTRAINT uq_retailer_feature UNIQUE (retailer_id, feature);
ALTER TABLE ONLY retailer_feature_assignments
    ADD CONSTRAINT fk_rfa_distributor FOREIGN KEY (distributor_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE ONLY retailer_feature_assignments
    ADD CONSTRAINT fk_rfa_retailer FOREIGN KEY (retailer_id) REFERENCES organizations(id) ON DELETE CASCADE;

CREATE INDEX idx_rfa_retailer ON retailer_feature_assignments (retailer_id);
CREATE INDEX idx_rfa_distributor ON retailer_feature_assignments (distributor_id);
