-- The free-project library: a small set of ready-made rooms anyone can open
-- without uploading a photo or spending a wall-detection credit.
--
-- The point of these tables is that they hold NO pixels. A template names the
-- storage keys of one photo and one PNG per wall, all of which live exactly once
-- under the shared "free-projects/" prefix. Starting a template copies ROWS —
-- a projects row, an uploaded_images row, one regions row per wall — and every
-- copy points back at those same keys. A thousand people opening the same
-- living room is a thousand cheap rows over one copy of the bytes, and the AI
-- never runs again for any of them: the masks were made once, when an admin
-- published the template.
--
-- The flip side of sharing the bytes is that no copy may ever delete them.
-- ProjectService skips blob deletion for keys under the library prefix, so a
-- user deleting their copy takes their rows and leaves the library intact;
-- deleting a template (admin only) is the one path that removes the files.
CREATE TABLE free_project_templates (
    id character varying(255) NOT NULL,
    -- Stable, human-readable handle. Also the storage folder, which is why it is
    -- restricted to [a-z0-9-] where it is written.
    slug character varying(120) NOT NULL,
    title character varying(160) NOT NULL,
    -- INTERIOR rooms are keyed by room ("LIVING_ROOM"); EXTERIOR ones by style
    -- ("TRADITIONAL", "MODERN"). One column serves both because the gallery only
    -- ever groups by space first, then by this key.
    space character varying(16) NOT NULL,
    room_key character varying(64) NOT NULL,
    room_label character varying(80) NOT NULL,
    description text,

    -- The photo, stored once. content type / size / dimensions are copied onto the
    -- uploaded_images row each copy gets, so cloning never has to read the file.
    image_storage_key character varying(512) NOT NULL,
    image_content_type character varying(100) NOT NULL,
    image_file_size bigint DEFAULT 0 NOT NULL,
    image_width integer,
    image_height integer,
    image_type character varying(32) DEFAULT 'UNKNOWN' NOT NULL,

    -- Set when the source project had been through the AI clean-up. The masks are
    -- aligned to THIS image when present, so a copy must carry it or the walls
    -- land in the wrong place.
    cleaned_image_storage_key character varying(512),

    -- Unpublished templates stay in the admin list and are refused by the start
    -- endpoint — somewhere to park one that needs its masks redone.
    published boolean DEFAULT true NOT NULL,
    display_order integer DEFAULT 0 NOT NULL,
    times_used bigint DEFAULT 0 NOT NULL,

    -- Where it came from, kept for the admin view only. Nulled rather than
    -- enforced: the source project may be deleted long before the template is.
    source_project_id character varying(255),
    created_by_user_id character varying(255),
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    CONSTRAINT free_project_templates_space_check
        CHECK ((space)::text = ANY ((ARRAY['INTERIOR'::character varying, 'EXTERIOR'::character varying])::text[]))
);

ALTER TABLE ONLY free_project_templates
    ADD CONSTRAINT free_project_templates_pkey PRIMARY KEY (id);

ALTER TABLE ONLY free_project_templates
    ADD CONSTRAINT free_project_templates_slug_key UNIQUE (slug);

-- The gallery reads "everything published, grouped by space then room, in the
-- admin's chosen order" — one index covers the whole page.
CREATE INDEX idx_free_project_templates_listing
    ON free_project_templates (published, space, room_key, display_order);

-- One row per paintable wall, holding the key of a mask PNG that was generated
-- once and is never regenerated. Mirrors the shape of `regions` closely enough
-- that cloning is a field-for-field copy.
CREATE TABLE free_project_template_regions (
    id bigint NOT NULL,
    template_id character varying(255) NOT NULL,
    label character varying(255),
    category character varying(32),
    mask_storage_key character varying(512) NOT NULL,
    -- The colour the template opens with, so a free project looks finished the
    -- moment it loads rather than showing bare walls. Optional.
    applied_hex_code character varying(32),
    applied_shade_code character varying(64),
    display_order integer DEFAULT 0 NOT NULL,
    CONSTRAINT free_project_template_regions_category_check
        CHECK ((category)::text = ANY ((ARRAY['MAIN_WALL'::character varying, 'ACCENT_WALL'::character varying,
                                              'OTHER_WALL'::character varying, 'TRIM'::character varying,
                                              'MANUAL'::character varying])::text[]))
);

ALTER TABLE free_project_template_regions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME free_project_template_regions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY free_project_template_regions
    ADD CONSTRAINT free_project_template_regions_pkey PRIMARY KEY (id);

-- Dropping a template takes its walls with it; the blobs are removed separately
-- by the service, which is the only thing allowed to touch library files.
ALTER TABLE ONLY free_project_template_regions
    ADD CONSTRAINT free_project_template_regions_template_fkey
        FOREIGN KEY (template_id) REFERENCES free_project_templates(id) ON DELETE CASCADE;

CREATE INDEX idx_free_project_template_regions_template
    ON free_project_template_regions (template_id, display_order);
