-- The shop's OWN choice of which paint companies it puts in front of people.
--
-- This is a different question from retailer_brand_assignments (V19), and the two
-- have to coexist. That table is the distributor's grant: the companies a shop is
-- PERMITTED to work with, decided upstream and not the shop's to widen. This one is
-- the shop's storefront decision: of the companies it may carry, which ones it
-- actually stocks and wants shown. A shop granted six companies that stocks two was
-- previously forced to display all six — at its own counter, in its kiosk, and to
-- every customer it onboarded — with no way to say otherwise.
--
-- The effective catalogue is the INTERSECTION of the two, resolved in
-- BrandAccessService. Keeping them apart is what makes a distributor's later revoke
-- bite immediately: narrowing the grant narrows what the shop shows, without the
-- shop's own selection silently re-granting a company that was taken away.
--
-- Same explicit-flag shape as brands_restricted and features_restricted, and for the
-- same reason: "no rows" cannot distinguish "never configured" (show everything) from
-- "the shop deselected every company" (show nothing). Defaults to false so every
-- existing shop keeps showing its full granted catalogue until it says otherwise.

ALTER TABLE organizations
    ADD COLUMN visible_brands_restricted boolean DEFAULT false NOT NULL;

CREATE TABLE shop_visible_brands (
    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    retailer_id character varying(255) NOT NULL,
    brand_id bigint NOT NULL,
    selected_at timestamp(6) without time zone
);

ALTER TABLE ONLY shop_visible_brands
    ADD CONSTRAINT shop_visible_brands_pkey PRIMARY KEY (id);
ALTER TABLE ONLY shop_visible_brands
    ADD CONSTRAINT uq_shop_visible_brand UNIQUE (retailer_id, brand_id);
ALTER TABLE ONLY shop_visible_brands
    ADD CONSTRAINT fk_svb_retailer FOREIGN KEY (retailer_id) REFERENCES organizations(id) ON DELETE CASCADE;
ALTER TABLE ONLY shop_visible_brands
    ADD CONSTRAINT fk_svb_brand FOREIGN KEY (brand_id) REFERENCES brands(id) ON DELETE CASCADE;

CREATE INDEX idx_svb_retailer ON shop_visible_brands (retailer_id);
