-- One-time OAuth exchange codes: the Google callback redirects with a short-lived
-- single-use code instead of real tokens (which are readable by extensions and
-- linger in browser history). Codes are stored SHA-256-hashed, expire in ~60s and
-- are consumed atomically on exchange.
CREATE TABLE oauth_exchange_codes (
    id bigint NOT NULL,
    user_id character varying(255) NOT NULL,
    code_hash character varying(255) NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    consumed boolean NOT NULL,
    created_at timestamp(6) without time zone
);

ALTER TABLE oauth_exchange_codes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME oauth_exchange_codes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY oauth_exchange_codes
    ADD CONSTRAINT oauth_exchange_codes_pkey PRIMARY KEY (id);

CREATE UNIQUE INDEX idx_oauth_exchange_hash ON oauth_exchange_codes (code_hash);
CREATE INDEX idx_oauth_exchange_user ON oauth_exchange_codes (user_id);
