-- Admin 2FA: one-time 6-digit email codes required on ADMIN logins whenever
-- mail delivery is configured. BCrypt-hashed, single-use, attempt-limited.
CREATE TABLE admin_login_codes (
    id bigint NOT NULL,
    user_id character varying(255) NOT NULL,
    code_hash character varying(255) NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    attempts integer NOT NULL,
    consumed boolean NOT NULL,
    created_at timestamp(6) without time zone
);

ALTER TABLE admin_login_codes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME admin_login_codes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY admin_login_codes
    ADD CONSTRAINT admin_login_codes_pkey PRIMARY KEY (id);

CREATE INDEX idx_admin_login_user ON admin_login_codes (user_id);
