-- Sign-in codes we text ourselves, as the cheap alternative to Firebase Phone Auth.
--
-- Firebase needs no DLT registration, which is why it went in first, and charges about
-- ₹6 a message for that. An Indian aggregator on a DLT-registered route carries the same
-- code for roughly 20 paise. Both flows prove the same fact and hand off to the same
-- PhoneAccountService; this table is what the second one needs.
--
-- Keyed to the NUMBER, not to a user — which is what separates it from
-- verification_codes and password_reset_codes, both of which belong to somebody already
-- known. This code runs BEFORE there is an account: the number may open an existing one
-- or become a new one, and which of those it is must not be decided, or revealed, when
-- the code is sent.
--
-- Same hardening as its siblings: the code is BCrypt-hashed so a database read hands
-- over no sign-ins, single-use, time-limited and attempt-limited.
CREATE TABLE phone_login_codes (
    id bigint NOT NULL,
    phone_number character varying(255) NOT NULL,
    code_hash character varying(255) NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    attempts integer NOT NULL,
    consumed boolean NOT NULL,
    -- What to call them if this number turns out to have no account. Asked for on the
    -- first screen, carried here, so the screen that takes the code has one field on it.
    sign_up_name character varying(100),
    created_at timestamp(6) without time zone
);

ALTER TABLE phone_login_codes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME phone_login_codes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY phone_login_codes
    ADD CONSTRAINT phone_login_codes_pkey PRIMARY KEY (id);

-- Every read is by number: the row lock on verify, the resend cooldown, and the daily
-- per-number cap that stops this endpoint being used to pester a stranger at our expense.
CREATE INDEX idx_phone_login_phone ON phone_login_codes (phone_number);

-- The cap counts rows in a 24-hour window and the cleanup deletes by expiry, so both
-- want the timestamps ordered rather than a scan of every code ever sent.
CREATE INDEX idx_phone_login_created ON phone_login_codes (created_at);
CREATE INDEX idx_phone_login_expires ON phone_login_codes (expires_at);
